### ISSUE TITLE
Throwing window to space makes the window take up the whole screen in the new space

### ISSUE THREAD

**Issue by smos08** [ianyh/Amethyst#1525] opened 2023-07-14 19:13 UTC
**Describe the bug**
if i am using the keyboard shortcut shift + ctrl + opt + 2 to the throw a window to space number 2, when the windows get to the space it is now the entire window and not the original size it was 

**Applications:**
all

**To Reproduce**
throw a window to a space using the keyboard shortcut

**Expected behavior**
the window would appear on the space the same size as in the window it left from

**Versions:**
 - macOS: 13.4
 - Amethyst: 0.19.0 (103)
 
**Debug Info**
```
Version: 0.19.0 (103)

OS version: Version 13.4 (Build 22F66)

Screens:
	(0.0, 0.0, 2560.0, 1440.0) [(0.0, 0.0, 2560.0, 1440.0)]

Configuration:
screen-padding-bottom: 0
floating-is-blacklist: 1
float-small-windows: 1
mouse-follows-focus: 0
enables-layout-hud: 1
enables-layout-hud-on-space-change: 0
floating: (
)
layouts: (
    floating
)
mouse-swaps-windows: 0
use-canary-build: 0
window-max-count: 0
window-resize-step: 5
ignore-menu-bar: 0
mod1: (
    option,
    shift
)
restore-layouts-on-launch: 0
screen-padding-top: 0
screen-padding-left: 0
window-margin-size: 0
debug-layout-info: 0
mod2: (
    option,
    shift,
    control
)
window-minimum-width: 0
new-windows-to-main: 0
focus-follows-mouse: 0
screen-padding-right: 0
follow-space-thrown-windows: 0
window-minimum-height: 0
window-margins: 0
```

**Additional context**
N/A

**Comment by ianyh** [comment] 2023-08-08 01:25
Duplicate of #1300

**Closed as completed by ianyh** 2023-08-08 01:25 UTC
Labels: duplicate
