### ISSUE TITLE
Can't toggle wether a window is floating.

### ISSUE THREAD

**Issue by gusberinger** [ianyh/Amethyst#396] opened 2016-02-06 00:24 UTC
On the iterm dev build, you can disable the title bar, but then Amethyst won't recognize the window. I tried 
```mod1 + t - toggle whether or not the focused window is floating``` but that had no effect on Amethyst.

**Comment by ianyh** [comment] 2016-02-06 00:24
Known problem, unfortunately. Duplicate of #200

**Closed** 2016-02-06 00:25 UTC
Labels: bug, duplicate
