### ISSUE TITLE
[Feature Request] Support match floating window by path or window title

### ISSUE THREAD

**Issue by Vxider** [ianyh/Amethyst#987] opened 2020-03-16 09:07 UTC
Some apps dose not has a bundle id, for example [scrcpy](https://github.com/Genymobile/scrcpy).

<img width="986" alt="截屏2020-03-1617 00 50" src="https://user-images.githubusercontent.com/6134315/76740143-5f582400-67a8-11ea-82f5-ad3f4db627f4.png">

Karabiner support an option to match by path, like the following configuration:

```
"conditions": [
    {
        "file_paths": [
            "^.*scrcpy"
        ],
        "type": "frontmost_application_if"
    }
]
```

Hope Amethyst can also support match floating window by path or window title.

**Comment by ianyh** [comment] 2020-03-30 02:14
Duplicate of #795

**Closed by ianyh** 2020-03-30 02:14 UTC
