### ISSUE TITLE
iTerm2 removing title bar makes amethyst ignore the window

### ISSUE THREAD

**Issue by thomaskern** [ianyh/Amethyst#200] opened 2014-08-25 09:12 UTC
I compiled iTerm2 after doing this http://www.patrickedelman.com/removing-the-title-bar-from-iterm2/ to it. Now i have no title bar. The thing is, new windows without the title bar are not being resized/placed by amethyst anymore.
why is that?

[Trello Card](https://trello.com/c/8aKYdTmg/68-amethyst-iterm2-removing-title-bar-makes-amethyst-ignore-the-window)

**Comment by Rnhmjoj** [comment] 2015-01-10 16:22
I didn't compile iterm but in the nightly builds there is now an option to hide the titlebar.
It is causing the same issue. Any updates?

**Comment by Hultner** [comment] 2015-03-08 00:03
I'm haven't written a line ObjC in probably 7 years and even then barely. Could anyone point me in the right direction for adding a custom patch/hack to fix this behaviour specifically for iTerm/whitelisted applications while waiting for a fix? 
Ping @ianyh @leonardt

**Comment by neonfrontier** [comment] 2015-04-20 03:04
@Hultner maybe you could take a look at how slate are doing it?
https://github.com/jigish/slate

**Comment by ddelnano** [comment] 2015-12-21 04:28
Started a fix for it [here](https://github.com/ianyh/Amethyst/pull/374).  The subrole of the title less windows is `AXDialog`. 

The focus aspect needs to be fixed but Amethyst now recognizes that it needs to tile the previously unrecognized windows.

**Comment by jclusso** [comment] 2016-01-25 19:41
I can confirm this issue too.

**Comment by ddelnano** [comment] 2016-01-25 19:42
Yea its because applications like Safari and Finder use the `AXDialog` so its not ideal to tile every window that has the `AXDialog` subrole.

**Comment by 0x62** [comment] 2016-05-11 20:37
Still an issue

**Comment by Ramblurr** [comment] 2016-10-31 13:12
Any updates on this issue? I'd love to use amethyst with a titlebar-less iterm2.

**Comment by net** [comment] 2017-01-11 05:46
@ianyh status on this issue?

**Comment by ianyh** [comment] 2017-01-30 15:06
It's tricky because the windows have the subrole `AXDialog`, which is true of a lot of things that you don't want to tile. Popups, for example, are also dialogs. There are probably some ways to differentiate popups from other things (they are modal, they have buttons, etc.). Could also just straight up whitelist iTerm, as there is a ton of demand for this.

**Comment by ddickstein** [comment] 2017-01-30 16:57
Oh speaking of which, Finder should probably always be treated as a
floating popup. When I open it I generally (1) use it very briefly, and (2)
want to interact with it while it's open (even if in full screen probably
would prefer a small finder appear on top of current app, because usually
using it to drag and drop or something alone those lines). At the very
least I think exposing that as a configurable setting would be helpful.

**Comment by BrowncoatShadow** [comment] 2017-01-31 15:15
@ddickstein You can already configure Finder windows to float by adding `com.apple.finder` to the "Floating" section in your preferences. That is not what this issue is about. MacOS classifies windows without title bars as a dialog, which normally should be floated. But, iTerm2 is an edge case that might require an exception.

**Comment by ericboehs** [comment] 2017-01-31 22:53
It seems we should make the white list customizable. The default options could include iTerm but would be removable if the user so chooses.

**Comment by ianyh** [comment] 2017-01-31 22:59
Yeah, there's an issue for tracking that #250

**Comment by MaxIsMyName** [comment] 2017-09-04 13:35
This has been open for three years now, any updates?

**Comment by ianyh** [comment] 2017-09-04 19:19
The short answer is no. It's on the list and it's high priority, but I haven't gotten to it.

**Comment by axs221** [comment] 2017-10-21 21:30
@MaxIsMyName I am not able to reproduce the issue, can you? I am on Amethyst 0.11.4, macOS Sierra 10.12.6, iTerm2 3.1.3. In iTerm2, you no longer need to compile from source like the article stated. I went to iTerm2 > Preferences > Profiles > Window > Style > No Title Bar. I opened a new window. Amethyst is handling the new window the same as standard windows.

**Comment by ianyh** [comment] 2017-10-21 22:54
Yeah, just tested it. It looks like in the most recent version they moved from using a dialog to using a custom-drawn window. So this may be fixed. Would like a few san-checks if possible, though, as my testing was brief and I'm not an iTerm user.

**Comment by ianyh** [comment] 2017-11-12 18:59
I'm going to close this as fixed. If someone runs into it again please reopen.

**Comment by purgat0ri** [comment] 2019-05-11 01:21
Running into it again, and setting different options under theme/tab bar location options doesn't make a difference.

**Comment by ianyh** [comment] 2019-05-11 18:36
🙃

**Comment by Dials-Mavis** [comment] 2019-07-02 05:08
Same issue here. Strangely enough when I send iTerm2 to another space it becomes tiled. However any new window is floating until I send it to another space first.

**Comment by ianyh** [comment] 2020-02-23 04:05
I can't reproduce on Build 3.3.9 of iTerm.

**Closed by ianyh** 2020-02-23 04:05 UTC
Labels: bug

**Comment by mTvare6** [comment] 2021-02-16 10:33
@thomaskern the [link](http://www.patrickedelman.com/removing-the-title-bar-from-iterm2/) you sent for removing iterm title is dead do you have another one or those instructions

**Comment by tkern** [comment] 2021-02-16 12:08
> @thomaskern the [link](http://www.patrickedelman.com/removing-the-title-bar-from-iterm2/) you sent for removing iterm title is dead do you have another one or those instructions

waybackmachine seems to have it indexed: https://web.archive.org/web/20150210111951/http://www.patrickedelman.com/removing-the-title-bar-from-iterm2/

edit: at this point, you can just change your "Profiles - Window - Style - No Title Bar" to get a title bar-less window
