### ISSUE TITLE
Focus follows mouse is too quick

### ISSUE THREAD

**Issue by freebrowser1** [ianyh/Amethyst#1121] opened 2021-05-25 17:31 UTC
**Describe the bug**
Enabling focus follows mouse has an immediate effect, which means that moving the mouse to another window which you want, the window below it captures the mouse pointer immediately. Most apps I use full screen, except a few apps with a small window such as 'System preferences'.
**Applications:**
All applications with a window not filling the entire screen and another application window behind it.
**To Reproduce**
Set all applications to 'Full screen' except a few where this is useless such as 'System Preferences', 'Terminal' or the Amethyst configuration window itself, add those to the 'automatically float windows' apps.

**Expected behavior**
There should be a short delay of e.g. half a second (adjustable) before the window under the mouse grabs focus.

**Screenshots**
If applicable, add screenshots to help explain your problem. In Ubuntu Linux there can be set a delay like this. 
See screenshot.

<img width="654" alt="Screenshot 2021-05-25 at 19 28 10" src="https://user-images.githubusercontent.com/26625141/119542426-cfd8d880-bd8f-11eb-8354-f8007d1ce1d1.png">

**Versions:**
 - macOS: 10.16.3
 - Amethyst: 0.15.4
 
**Debug Info**
```
Version: 0.15.4 (91)

OS version: Version 11.3.1 (Build 20E241)

Has permissions: true

Screens:
	(0.0, 0.0, 1280.0, 800.0) [(0.0, 0.0, 1280.0, 800.0)]

Manageable applications:
	Firefox (org.mozilla.firefox)
	AppSSOAgent (com.apple.AppSSOAgent)
	talagent (com.apple.talagent)
	Terminal (com.apple.Terminal)
	ForkLift (com.binarynights.ForkLift-3)
	LibreOffice (org.libreoffice.script)
	KeePassXC (org.keepassxc.keepassxc)
	Dock Clock (com.ilifetouch.dockclock)
	Finder (com.apple.finder)
	coreautha (com.apple.LocalAuthentication.UIAgent)
	Preview (com.apple.Preview)
	VeraCrypt (org.idrix.VeraCrypt)
	Xee³ (cx.c3.Xee3)
	Mail (com.apple.mail)
	Atom (com.github.atom)
	System Preferences (com.apple.systempreferences)
	VNC Viewer (com.realvnc.vncviewer)

Configuration:
enables-layout-hud-on-space-change: 0
focus-follows-mouse: 1
screen-padding-right: 0
ignore-menu-bar: 1
window-margin-size: 0
mod2: (
    option,
    shift,
    control
)
float-small-windows: 1
floating-is-blacklist: 1
mouse-follows-focus: 0
mod1: (
    option,
    shift
)
follow-space-thrown-windows: 0
window-minimum-width: 890
window-margins: 0
floating: (
        {
        id = "com.apple.Terminal";
        "window-titles" =         (
        );
    },
        {
        id = "org.virtualbox.app.VirtualBox";
        "window-titles" =         (
        );
    },
        {
        id = "com.radiosilenceapp.client";
        "window-titles" =         (
        );
    },
        {
        id = "/Users/myuser/homebrew/bin/scrcpy";
        "window-titles" =         (
            "ONEPLUS A6003"
        );
    },
        {
        id = "org.idrix.VeraCrypt";
        "window-titles" =         (
        );
    },
        {
        id = "com.apple.systempreferences";
        "window-titles" =         (
        );
    },
        {
        id = "com.electron.transferagent";
        "window-titles" =         (
        );
    },
        {
        id = "com.realvnc.vncviewer";
        "window-titles" =         (
        );
    }
)
window-resize-step: 10
layouts: (
    fullscreen,
    fullscreen,
    fullscreen
)
screen-padding-left: 0
new-windows-to-main: 1
mouse-swaps-windows: 1
screen-padding-top: 0
restore-layouts-on-launch: 1
window-minimum-height: 500
enables-layout-hud: 0
debug-layout-info: 1
screen-padding-bottom: 0
use-canary-build: 0
```

**Comment by 0xConnorRhodes** [comment] 2021-06-29 15:17
I really appreciate the instant nature of "focus follows mouse." That's pretty core to my workflow. If you do add a configuration option for this, please allow the option to be adjusted all the way down to a 0 ms delay.

That being said, assuming this option can be adjusted to 0 ms, I can see the value in adding it. The ability to customize the "focus follows mouse" delay would make Amethyst more flexible for different workflows.

**Comment by ianyh** [comment] 2021-07-03 01:13
Duplicate of #638

**Closed as completed by ianyh** 2021-07-03 01:13 UTC
Labels: duplicate, enhancement
