### ISSUE TITLE
Amethyst consistently lags for several seconds, unknown reason.

### ISSUE THREAD

**Issue by viclib** [ianyh/Amethyst#283] opened 2015-01-22 04:54 UTC
Sometimes "Amethyst" is semi-smooth - it takes 0.3~0.8ms to switch from a window to another, which is not perfect, but acceptable. Sometimes, though, it takes as much as 10 full seconds. It works like that: I press `CMD+J` (my switch hotkey) and it doesn't do anything. I click with the mouse on the window, and after I'm actually working on it, Amethyst triggers the switch to the window I was before. When this happens, I noticed that clicking on the Amethyst icon doesn't do anything - as if the application is stuck in a loop. Any idea why that would happen?

Must add this is, by far, the most annoying thing about my Yosemite and one of the reasons I'm considering Ubuntu (since Amethyst is the only decent window manager on OSX). I'm willing to donate a symbolic $30 if the devs are able to make it 100% smooth (<0.05ms always). Not much, but I'm a college student from a poor country so... you know.

Thanks!

**Comment by ianyh** [comment] 2015-01-22 12:52
Duplicate of #209

**Closed by ianyh** 2015-01-22 12:52 UTC
Labels: duplicate

**Comment by viclib** [comment] 2015-01-23 17:30
Oh I completely forgot about that. My bad.
