### ISSUE TITLE
A single shortcut to equalize the widths of windows (e.g a layout called "equal column layout" or a command "equalize windows")

### ISSUE THREAD

**Issue by cj650498** [ianyh/Amethyst#1469] opened 2023-03-29 20:52 UTC
**Is your feature request related to a problem? Please describe.**

If I'm in _any_ kind of layout that has two or more windows, all in columns, (e.g regardless if using two windows in tall layout, any of the column layouts, two pane layout, etc.) there does not seem to be a single shortcut to equalize the widths of all windows.

The only layout that _almost_ works for two windows is the two pane layout, that initially snaps the two windows into two equal columns. The problem is, if I shrink or expand either window then there's no single shortcut to equalize them back, even if I run the shortcut for the two pane layout again they stay where I expanded/shrank them to instead of the initial equal widths they started at.

Another solution that _almost_ works for 3column layout is to use 3column middle. But again, they aren't equal, it's just the best I've got.

**Describe the solution you'd like**

I think the solution I want would be a shortcut that works as follows:

If and only if all windows are in columns then equalize all their widths. If they are not in columns (e.g. three windows in tall layout, etc.) then the shortcut should do nothing. I think this feature would work best if it could recognize if all windows are in columns no matter what layout happens to be "active" (e.g regardless if using two windows in tall layout, any of the column layouts, two pane layout, etc.)

A good name for this layout could be "equal column layout."

<sub>I guess it doesn't have to be just columns, equalizing the widths of all windows on one screen seems useful as well and would work for my issue too. I just want it to _at least_ have this work for columns. There could be a shortcut "equalize window widths" and "equal column layout."</sub>

**Describe alternatives you've considered**

The only alternative I use for two windows is: using two pane layout and not expanding or shrinking either window, and if I do need to expand or shrink a window I go into column layout and move them, and then when I want them back to equal I go back to two pane layout (this seems to be the only way to retain the equal widths in two pane layout).

The only alternative I use for three windows is just sticking with 3column middle layout and if I want them all equal I just have to adjust them individually.

**Additional context**

Apologies if this already exists and I just haven't found it. I searched around a little bit and played with the preferences and couldn't find a single command to equalize column windows.

Thanks for any consideration!

**Comment by ianyh** [comment] 2023-04-05 11:24
I think this is a duplicate of #1387.

**Closed as not planned** 2023-04-05 11:24 UTC
