### ISSUE TITLE
Support for more than 9 spaces

### ISSUE THREAD

**Issue by mitar** [ianyh/Amethyst#611] opened 2017-07-07 05:27 UTC
## System

 - **Amethyst version**: 0.10.1 (37)
 - **macOS version**: 10.10.5

## What's the problem?

Currently it seems I can send windows only to first 9 spaces. It would be great if there would be support for any number of spaces (I have 10).

**Comment by ianyh** [comment] 2017-07-07 18:45
The basic problem is that the default shortcuts use single digits, so this is either fixed by #595 which adds a 10th space or is a duplicate of #409 which would allow an arbitrary number of spaces.

**Closed by ianyh** 2017-07-07 18:45 UTC
