### ISSUE TITLE
Twitter.app in tall mode behaves as if it is wider than it is

### ISSUE THREAD

**Issue by wmonk** [ianyh/Amethyst#380] opened 2016-01-08 12:36 UTC
**To reproduce:**
1. Open up Chrome and Twitter.app (os x)
2. Put amethyst into tall mode
3. Twitter behaves as if it is 1/2 the screen, but there is a large gap to the right of it

**Screenshot**
![screen shot 2016-01-08 at 12 35 34](https://cloud.githubusercontent.com/assets/175278/12198042/625d1e12-b604-11e5-9c88-6d2c813db43e.png)

I assume this is because Twitter is built in a way that it cannot be expanded more than a certain width.

[Trello Card](https://trello.com/c/howZwh0X/188-amethyst-twitter-app-in-tall-mode-behaves-as-if-it-is-wider-than-it-is)

**Comment by wmonk** [comment] 2016-01-08 12:37
Also thanks for Amethyst, it is amazing! :smile:

**Comment by ianyh** [comment] 2016-01-13 22:27
Thank you! Glad you like it.

Yeah, Twitter has a constant width. There's a few other common ones that fall into this. System Preferences is the one that I run into a lot. There's not really a way to change the size of the window, and even if you could you'd potentially be breaking app layouts.

Do you have thoughts on what the expected behavior was for you?

**Comment by jmccance** [comment] 2017-03-28 19:17
I've noticed this as well with Tweetbot. For me, what I'd expect (at least in the "tall" layout) is for the other window to fill the remaining space so that there aren't any gaps. So if `x` and `o` are two different windows and `x` is Tweetbot, I'd expect that instead of this:

```
xx...ooo
xx...ooo
```

I'd get this:

```
xxoooooo
xxoooooo
```

Same on the other side:

```
// Not this
oooxx...
oooxx...

// Instead this
ooooooxx
ooooooxx
```

Obviously this falls apart if you have two windows with maximum width, but that doesn't come up often for me.

**Comment by ianyh** [comment] 2017-11-12 19:16
Duplicate of #4

**Closed by ianyh** 2017-11-12 19:16 UTC
Labels: bug
