### ISSUE TITLE
'throw to window' doesn't work anymore after updating to macOS Sequoia

### ISSUE THREAD

**Issue by rkristelijn** [ianyh/Amethyst#1701] opened 2024-12-12 08:30 UTC
**Describe the bug**
I was working very happy with only the 'throw to window' shortcuts enabled. I believe after updating to macOS Sequoia the shortcuts don't work anymore. 

**Applications:**
What applications are involved? Any application/window

**To Reproduce**

i have ⌃ ⌥ ⇧ ⬅ and ➡  linked to throw to next window, nothing happens when I press the shortcut key combo, also not for 1,2,3... i believe those settings to be default.

**Expected behavior**

I expect to throw the window to the  respective space

**Screenshots**

**Versions:**
 - macOS: macOS Sequoia 15.1.1
 - Amethyst: v0.75 (81)
 
**Debug Info**
```
$ /Applications/Amethyst.app/Contents/MacOS/Amethyst --debug-info [--include-apps]
```
Note: `--include-apps` will list your manageable applications, but is optional if you don't want to list that.

**Additional context**

**Comment by ianyh** [comment] 2024-12-12 12:41
Duplicate of #1676

**Closed as not planned** 2024-12-12 12:41 UTC
