### ISSUE TITLE
Unable to float Android Emulator

### ISSUE THREAD

**Issue by dapicester** [ianyh/Amethyst#928] opened 2020-01-09 06:10 UTC
## System

 - **Amethyst version**: 0.14.3 (79)
 - **macOS version**: 10.14.6 (18G1012)

## What's the problem?
I am unable to float the Android Emulator.

I believe it's related to #748 because the window title is empty when it is first created.
I also tried to create custom floating rule in settings with no success:

![Screen Shot 2020-01-09 at 14 13 01](https://user-images.githubusercontent.com/3007132/72042756-518aac00-32ea-11ea-8588-aa8ddc6b262e.png)

Note that I added an empty `bundleID` because the `qemu` application has no `bundleID` set, as I can see from the output of `lsappinfo`:
```
55) "qemu-system-x86_64" ASN:0x0-0x19a89a7:
    bundleID=[ NULL ]
    bundle path="/Users/paolo/Library/Android/sdk/emulator"
    executable path="/Users/paolo/Library/Android/sdk/emulator/qemu/darwin-x86_64/qemu-system-x86_64"
    pid = 59620 type="Foreground" flavor=2 Version=[ NULL ]  fileType="BNDL" creator="????" Arch=x86_64
    originalExecutablePath="/Users/paolo/Library/Android/sdk/emulator/emulator" originalPid=59620
    checkin time = 2020/01/09 14:06:18 ( 10 minutes, 7.95851 seconds ago )
```

**Comment by ianyh** [comment] 2020-02-09 20:49
I think this is a duplicate of #795.

**Closed by ianyh** 2020-02-09 20:49 UTC
