### ISSUE TITLE
Unable to throw window to spaces left or right

### ISSUE THREAD

**Issue by nahoskins** [ianyh/Amethyst#1655] opened 2024-05-28 11:36 UTC
**Describe the bug**
Engaging the keys defined for the purpose fails to move windows to spaces to the left or right

**Applications:**
What applications are involved?
All

**To Reproduce**
Sonoma 14.5
Amethyst 0.21.0 110

**Expected behavior**
The window to be pushed into the adjacent space

**Screenshots**
Not applicable.

**Versions:**
Sonoma 14.5
Amethyst 0.21.1 111
 
**Debug Info**
```
$ /Applications/Amethyst.app/Contents/MacOS/Amethyst --debug-info [--include-apps]
```
Note: `--include-apps` will list your manageable applications, but is optional if you don't want to list that.
```
Version: 0.21.0 (110)

OS version: Version 14.5 (Build 23F79)

Screens:
	(0.0, 0.0, 1496.0, 967.0) [(0.0, 0.0, 1496.0, 967.0)]
	(1496.0, -450.0, 3360.0, 1890.0) [(1496.0, -473.0, 3360.0, 1890.0)]

Configuration:
floating-is-blacklist: 1
restore-layouts-on-launch: 1
enables-layout-hud-on-space-change: 0
layouts: (
    tall,
    wide,
    fullscreen,
    column,
    "middle-wide",
    "3column-right",
    "3column-left",
    bsp,
    "widescreen-tall"
)
screen-padding-bottom: 0
screen-padding-left: 0
window-margin-size: 0
mouse-follows-focus: 1
mod1: (
    option,
    shift
)
debug-layout-info: 0
mod2: (
    option,
    shift,
    control
)
floating: (
        {
        id = "com.apple.Stickies";
        "window-titles" =         (
        );
    },
        {
        id = "com.openai.chat";
        "window-titles" =         (
        );
    }
)
use-canary-build: 0
new-windows-to-main: 0
window-resize-step: 5
window-max-count: 0
ignore-menu-bar: 0
window-minimum-height: 0
focus-follows-mouse: 0
enables-layout-hud: 1
window-margins: 0
window-minimum-width: 0
screen-padding-top: 0
float-small-windows: 0
follow-space-thrown-windows: 1
screen-padding-right: 0
```
**Additional context**

**Comment by Cerebus** [comment] 2024-05-28 13:31
Same for 0.21.1 (111) (homebrew installed) on macOS 14.5.

**Comment by johnnymugs** [comment] 2024-05-28 15:03
Duplicate of https://github.com/ianyh/Amethyst/issues/1643 ?

**Comment by Cerebus** [comment] 2024-05-28 15:16
> Duplicate of #1643 ?

Only if someone reopens it.  Throwing a window on 0.21.1 still doesn't work on 14.5; something definitely happens b/c I can see the rolling flicker as all windows redraw, but the target window doesn't move.

**Comment by cfritze64** [comment] 2024-05-28 15:54
seeing same behaviour as Cerebus

**Comment by Vinh-CHUC** [comment] 2024-05-28 18:19
also happens for me with homebrew build, will try with github release page one. They should be the same though no?

**Comment by tthn0** [comment] 2024-05-29 04:07
I also have this issue, but I'm on an M1 MacBook Air

**Comment by alexgenaud** [comment] 2024-05-29 11:23
This issue arose immediately following Mac OS X update to Sonoma 14.5 (it also botched up several utilities like sed).

Not only "throw left and right" but all "throw" (to any named/numbered desktop) is broken.

**Comment by Cerebus** [comment] 2024-05-29 12:40
To be clear: This is on Macbook Pro 2017, so that's Intel Core i7.

**Comment by ianyh** [comment] 2024-05-29 12:45
Updated the ticket info to track the issue on Intel.

**Comment by cywang117** [comment] 2024-05-29 22:26
I'm on an M2 Mac, and am also experiencing the issue. This also occurred for me after an OS upgrade to Sonoma 14.5, so perhaps it's tied to OS version?

**Comment by philniko** [comment] 2024-05-29 22:27
I am an M1 mac user as well, same issue. It is not an intel-specific issue it seems.

**Comment by ianyh** [comment] 2024-05-29 22:28
Interesting! I'll try to look deeper.

**Comment by edshee** [comment] 2024-05-30 06:50
I'm also having this issue on an M2 macbook air (Sonoma 14.5). Amethyst version 0.21.0.

**Comment by toostn** [comment] 2024-05-30 06:54
Same thing happens for me after the most recent MacOS update. Running on a system patched with Open Core legacy patcher, if that matters, but all worked fine before the MacOS update.

Tried to change to other hotkey combo, but same results. The active window just flickers and doesn't change space.

There are some console messages from Amethyst reading "[0x7ff13f006ea0] Channel could not return listener port." Don't know if might somehow be related.

Please let me know if I could help in debugging somehow.

**Comment by lukashr** [comment] 2024-06-02 14:14
Hi, I've been having the same problem. I've found that it's related to full screen apps. At least in my case. When full screen apps are on the "right" side in Mission Control, everything works fine. But when I move the "with mouse from Mission Control" full screen app to the left, it stops working. Eg. when first "space" is fullscreen app, from Mission Control perspective, then throwing does not work. 

I'm using an M1 CPU, macOS 14.5, and Amethyst 0.21.1.

**Comment by cosmalabadeusz** [comment] 2024-06-02 17:34
+1
macbook m3
Sonoma 14.5
Amethyst version 0.21.1.

**Comment by Cerebus** [comment] 2024-06-03 13:07
> Hi, I've been having the same problem. I've found that it's related to full screen apps. At least in my case. When full screen apps are on the "right" side in Mission Control, everything works fine. But when I move the "with mouse from Mission Control" full screen app to the left, it stops working. Eg. when first "space" is fullscreen app, from Mission Control perspective, then throwing does not work.
> 
> I'm using an M1 CPU, macOS 14.5, and Amethyst 0.21.1.

All my spaces are in 3-column middle, and I rarely (if ever) use macOS fullscreen.

**Comment by nahoskins** [comment] 2024-06-03 17:50
Some further system information:
```
 Model Name:	MacBook Pro
  Model Identifier:	Mac15,9
  Model Number:	MUW63LL/A
  Chip:	Apple M3 Max
  Total Number of Cores:	16 (12 performance and 4 efficiency)
  Memory:	48 GB
  System Firmware Version:	10151.121.1
  OS Loader Version:	10151.121.1
  
  ```

**Comment by itsrimzz1** [comment] 2024-06-04 03:52
+1. Same for 2019 Intel Macbook pro. Happened immediately after upgrade to Sanoma 14.5

**Comment by xerebus** [comment] 2024-06-04 13:29
+1 on M3 Max MBP, 0.21.0 (will update). I have two displays with separate spaces on each. Throwing between spaces on the same display does not work at all (I don't see the "flicker" others are mentioning, the window just stays put), while throwing between spaces on different displays always throws the window to the active space on the new display.

**Comment by DanCates** [comment] 2024-06-04 13:42
I'm running an M1 Macbook Pro 16". Upgraded to MacOS 14.5 last night and experienced the throwing issue this morning. Upgraded Amethyst to 0.21.1 just now and [throwing works again--albeit for non-fullscreen apps](https://www.loom.com/share/3959f5bc700449c4b9eb1085b5c4f22f?sid=e33eccdf-f78d-4b9e-a32f-fa420dae339d). As long as I'm using Amethyst to manage windows instead of Mission Control, it works. 

No offense to others but, if you have Amethyst to manage your windows, why are you still using Mission Control to manage windows? You can easily use Amethyst to accomplish the same effect but better. I never even attempted to use Mission Control for window management ever since I started using Amethyst like 10 months ago so I never attempted to throw a window managed by Mission Control. It's true that it doesn't work for me in 0.21.1, but I never would have known it worked before because I never used it.

**Comment by nahoskins** [comment] 2024-06-05 01:57
> I'm running an M1 Macbook Pro 16". Upgraded to MacOS 14.5 last night and experienced the throwing issue this morning. Upgraded Amethyst to 0.21.1 just now and [throwing works again--albeit for non-fullscreen apps](https://www.loom.com/share/3959f5bc700449c4b9eb1085b5c4f22f?sid=e33eccdf-f78d-4b9e-a32f-fa420dae339d). As long as I'm using Amethyst to manage windows instead of Mission Control, it works. 
> 
> No offense to others but, if you have Amethyst to manage your windows, why are you still using Mission Control to manage windows? You can easily use Amethyst to accomplish the same effect but better. I never even attempted to use Mission Control for window management ever since I started using Amethyst like 10 months ago so I never attempted to throw a window managed by Mission Control. It's true that it doesn't work for me in 0.21.1, but I never would have known it worked before because I never used it.

What do you mean by "a window managed by mission control"?

**Comment by nahoskins** [comment] 2024-06-05 12:45
At least for me, this issue is closed by the 0.21.1 release.

**Comment by DanCates** [comment] 2024-06-05 13:37
> What do you mean by "a window managed by mission control"?

[This is a demo of what I mean](https://www.loom.com/share/db1885798ec6406d803ceedcd5b7dcc0?sid=3113c160-859b-4461-9f25-b63fa13690e8) by "a window managed by Mission Control". Copied someone else who referred to it that way in their post. But it seems like the correct terminology [based on what Mac has called "Mission Control" historically](https://en.wikipedia.org/wiki/Mission_Control_(macOS)). It is their name for the group of MacOS features used to manage windows.

**Comment by philtim** [comment] 2024-06-05 15:50
With the 0.21.1 version I can throw windows to various spaces again. Thanks for fix 👍🏼

**Comment by nahoskins** [comment] 2024-06-05 16:13
> At least for me, this issue is closed by the 0.21.1 release.

Alas. The error persists. It worked on first updating to 0.21.1 but it is back this afternoon.

It is not immediately apparent that anything has changed.

**Comment by nahoskins** [comment] 2024-06-05 16:32
> > What do you mean by "a window managed by mission control"?
> 
> [This is a demo of what I mean](https://www.loom.com/share/db1885798ec6406d803ceedcd5b7dcc0?sid=3113c160-859b-4461-9f25-b63fa13690e8) by "a window managed by Mission Control". Copied someone else who referred to it that way in their post. But it seems like the correct terminology [based on what Mac has called "Mission Control" historically](https://en.wikipedia.org/wiki/Mission_Control_(macOS)). It is their name for the group of MacOS features used to manage windows.

I don't understand your original comment in this context.

If we both understand Mission Control as the group of MacOS features used to manage windows, and not some property of a window itself denoting a hierarchy of responsibility, then what do you mean when you say:

> I never attempted to throw a window managed by Mission Control

All windows are 'managed' by Mission Control. In the sense that those features are built into the OS. In the same way that DWM 'manages' X windows in Linux, even if you decide to use an alternate tiling manager adjacent to it.

Are you saying you've never thrown a window to another space? Or are you suggesting that you have thrown windows that were not managed by Mission Control?

Maybe you meant you didn't use Mission Control to throw the window to another space?

In which, case you were using Amethyst to do this, which is exactly the feature this issue is related to?

> It's true that it doesn't work for me in 0.21.1, but I never would have known it worked before because I never used it.

What doesn't work for you in 0.21.1? Throwing windows to other spaces? Something else?

You say:
> As long as I'm using Amethyst to manage windows instead of Mission Control, it works.

What do you mean by 'it works' then?

No offense but the comment you posted is egregiously difficult to understand.

In any case, the issue seems to be intermittent on my machine in 0.21.1 but is not solved.

@ianyh if there is anything else I can provide to assist please let me know.

**Comment by douglassd** [comment] 2024-06-05 16:46
I've got 2 macbooks, one intel, one M3, both running 0.21.1. Throwing windows IS working on the M3, which is connected to an external monitor (note, only the external monitor is in use, not the laptop display). Throwing windows on the intel machine, using only the laptop display IS NOT working.

I'll do some more testing with/without external monitor, but could this explain the intermittent behavior you're experiencing @nahoskins ?

**Comment by DanCates** [comment] 2024-06-05 17:07
> No offense but the comment you posted is egregiously difficult to understand.

😂 Good one. None taken.

What did you think about my screen recording demonstrating and explaining what I was talking about? Did that provide clarity? Sorry my attempt to explain things in writing was riddled with confusing statements. [Here's the link again](https://www.loom.com/share/db1885798ec6406d803ceedcd5b7dcc0?sid=3113c160-859b-4461-9f25-b63fa13690e8) if it helps.

**Comment by nahoskins** [comment] 2024-06-05 17:47
Currently, using 0.21.1

I am unable to:
Throw focused window to space left (or right)

I am able to:
Swap focused window to screens, both clockwise and counter clockwise.
I am able to throw focused window to spaces via their numerical id (1,2 ...)

As far as I can tell the issue is limited to swapping to adjacent spaces. (which is what I use the most, naturally!)

It DID work, very briefly, after I updated. It was only able to throw spaces to the right, but it did do that for a short time. Now it does neither left nor right.

One interesting note, the render flash, occurs when I try to move spaces left, but not right.

And to add, I am using an external monitor (dimensions I believe are listed in the output I posted above).

I am not using any full screen apps.

**Comment by nahoskins** [comment] 2024-06-05 18:02
> > No offense but the comment you posted is egregiously difficult to understand.
> 
> 😂 Good one. None taken.
> 
> What did you think about my screen recording demonstrating and explaining what I was talking about? Did that provide clarity? Sorry my attempt to explain things in writing was riddled with confusing statements. [Here's the link again](https://www.loom.com/share/db1885798ec6406d803ceedcd5b7dcc0?sid=3113c160-859b-4461-9f25-b63fa13690e8) if it helps.

So when you say 'throw windows' you were referring to moving windows into the left and right splits of the screen is that correct?

I at least, do not use full screen or split screen windows with Amethyst. I, like you I imagine, use Amethyst exclusively for managing windows and do not split spaces or use full screen spaces.

It sounds like you originally thought the issue was with throwing split spaces or full screen spaces then, I never would have thought to try that.

The issue is with bob standard, iterm2 windows not moving to adjacent spaces when I tell Amethyst to do so via the keyboard shortcut designated for it.

Let me know if I'm still misunderstanding you.

**Comment by nahoskins** [comment] 2024-06-05 18:12
OK after uninstalling the homebrew version and rebooting. It appears 0.21.1 DOES throw left and right.

This behaviour is then broken when you fullscreen an app. This seems like a separate issue to me. Marking Closed.

**Comment by ianyh** [comment] 2024-06-05 18:14
Oh, I hadn't considered brew installations! Could someone who has installed via homebrew confirm for me that the fix is working for them?

**Comment by roaldarbol** [comment] 2024-06-05 18:29
I'm using homebrew (v0.21.1) - doesn't seem to work for me (I'm a recent user, so I haven't used it when it was working - I'm imagining that it should "swap" two windows within a screen?). Also throwing to a specific number (1) only works for a second, then is reversed.

**Comment by nahoskins** [comment] 2024-06-05 18:31
Specifically, if I have a fullscreen window on my primary display, amethyst is unable to throw windows to adjacent spaces.

I've just confirmed the brew install has the fix. I have created a new issue related to the fullscreened windows breaking the adjacent window throw.

**Comment by douglassd** [comment] 2024-06-05 18:32
> Oh, I hadn't considered brew installations! Could someone who has installed via homebrew confirm for me that the fix is working for them?

Both my installations are via homebrew. Both installations are running version 0.21.1 (111)

M3 Macbook using only a single, external monitor, able to throw a window to space using either throw left/right or throw to a specific space number.

Intel Macbook using only the laptop display, NOT able to throw windows.

Intel Macbook using only a single, external monitor (same as used with M3), NOT able to throw windows.

Here's debug info from intel macbook while connected to external monitor:

```
Version: 0.21.1 (111)

OS version: Version 14.5 (Build 23F79)

Screens:
	(0.0, 0.0, 2560.0, 1440.0) [(0.0, 0.0, 2560.0, 1440.0)]

Configuration:
debug-layout-info: 0
window-minimum-width: 0
floating: (
        {
        id = "com.apple.systempreferences";
        "window-titles" =         (
        );
    },
        {
        id = "com.apple.FontBook";
        "window-titles" =         (
        );
    },
        {
        id = "com.apple.ActivityMonitor";
        "window-titles" =         (
        );
    },
        {
        id = "com.microsoft.rdc.macos";
        "window-titles" =         (
        );
    },
        {
        id = "com.apple.calculator";
        "window-titles" =         (
        );
    },
        {
        id = "com.apple.Stickies";
        "window-titles" =         (
        );
    },
        {
        id = "com.apple.backup.launcher";
        "window-titles" =         (
        );
    },
        {
        id = "com.apple.FaceTime";
        "window-titles" =         (
        );
    },
        {
        id = "com.toggl.daneel";
        "window-titles" =         (
        );
    }
)
floating-is-blacklist: 1
use-canary-build: 0
screen-padding-bottom: 0
window-resize-step: 5
mod1: (
    option,
    shift
)
new-windows-to-main: 0
screen-padding-right: 0
follow-space-thrown-windows: 1
window-minimum-height: 0
mod2: (
    option,
    shift,
    control
)
restore-layouts-on-launch: 1
ignore-menu-bar: 0
screen-padding-top: 0
screen-padding-left: 0
window-margins: 0
enables-layout-hud: 1
window-max-count: 0
window-margin-size: 0
enables-layout-hud-on-space-change: 0
mouse-follows-focus: 0
float-small-windows: 1
focus-follows-mouse: 0
layouts: (
    tall,
    wide,
    fullscreen,
    column,
    "middle-wide",
    floating
)
```

**Comment by roaldarbol** [comment] 2024-06-05 18:34
Same as @douglassd, on Intel Mac, not working. Definitely an additional issue with the full screens, but even without them it doesn't work. Jumps over and then right back again within a second.

**Comment by douglassd** [comment] 2024-06-05 18:35
Agreed @roaldarbol , and confirming that I was testing without any fullscreen apps

**Comment by DanCates** [comment] 2024-06-05 19:34
> So when you say 'throw windows' you were referring to moving windows into the left and right splits of the screen is that correct?
> 
> I at least, do not use full screen or split screen windows with Amethyst. I, like you I imagine, use Amethyst exclusively for managing windows and do not split spaces or use full screen spaces.
> 
> It sounds like you originally thought the issue was with throwing split spaces or full screen spaces then, I never would have thought to try that.

I believe you've got what I was trying to say for the most part. I'll separate categories below to more clearly present what I experienced:

**NORMAL WINDOWS USING AMETHYST FOR SPLIT-SCREEN OR FULLSCREEN LAYOUT**
This is how I normally manage my windows using the Amethyst functions and keyboard shortcuts.
- I can successfully throw them in three scenarios: 
     1) Left and right across Spaces within the same screen (monitor), 
     2) To non-adjacent, numbered spaces within the same screen (monitor), and 
     3) Across screens (monitors) on the current spaces. e.g. From monitor 1 to monitor 3, to whatever space is currently present on each monitor.
- After I upgraded to MacOS 14.5 and Amethyst 0.21.0, all of the above scenarios were broken. Upon updating to 0.21.1, they were all fixed.

**FULL-SCREEN AND SPLIT-SCREEN using Spaces / Mission Control (not amethyst)**
I had never tried using these windows with Amethyst before today but @lukashr mentioned having trouble with them in his post earlier in this thread. So I experimented with them and found:
- I cannot throw these windows in any scenario.
- Screen goes black when attempting.
- This is experienced while running Amethyst 0.21.1

**Comment by Vinh-CHUC** [comment] 2024-06-06 10:53
@ianyh why would there be a difference between the homebrew and the github builds?

In my case it's still broken even when using the github build, to be clear I'm not trying to do it with fullscreen windows

I got a intel mbp16 from 2019

**Comment by Vinh-CHUC** [comment] 2024-06-06 11:06
@nahoskins does this still work for you? could you reopen it's definitely broken for some people

**Comment by nahoskins** [comment] 2024-06-06 13:40
It appears that this is still an open issue, seemingly specific to Intel based Macs, on the 0.21.1 release and 14.5 MacOS

**Comment by nahoskins** [comment] 2024-06-06 13:42
> @nahoskins does this still work for you? could you reopen it's definitely broken for some people

This issue does not occur on my m3 machine running 0.21.1 (111)

I do still have an issue when an app is in 'full screen' mode which I have created a separate issue for #1660

**Comment by noel-yap** [comment] 2024-06-12 15:06
> Author

This isn't specific to Intel-based Macs. I have a MacBook Pro with M1 Max and am also not able to throw windows since upgrading to Sonoma 14.5

**Comment by edshee** [comment] 2024-06-12 15:12
> > Author
> 
> This isn't specific to Intel-based Macs. I have a MacBook Pro with M1 Max and am also not able to throw windows since upgrading to Sonoma 14.5

have you tried upgrading to 0.21.1? That fixed the issue for me

**Comment by magoz** [comment] 2024-06-12 16:16
Same issue here. I can't throw windows.

- Amethyst 0.21.1 (111) Installed via Hombrew
- Intel Mac (16-inch, 2019)
- macOS Sonoma (14.5)

**Comment by noel-yap** [comment] 2024-06-12 16:46
> > > Author
> > 
> > 
> > This isn't specific to Intel-based Macs. I have a MacBook Pro with M1 Max and am also not able to throw windows since upgrading to Sonoma 14.5
> 
> have you tried upgrading to 0.21.1? That fixed the issue for me

Trying to upgrade from 0.21.0, Amethyst says I'm at the latest

**Comment by roaldarbol** [comment] 2024-06-12 16:50
> > > > Author
> > > 
> > > 
> > > This isn't specific to Intel-based Macs. I have a MacBook Pro with M1 Max and am also not able to throw windows since upgrading to Sonoma 14.5
> > 
> > 
> > have you tried upgrading to 0.21.1? That fixed the issue for me
> 
> Trying to upgrade from 0.21.0, Amethyst says I'm at the latest

You need to enable development builds.😊 `Preferences` > `Debug` > `Get development builds`

**Comment by Vinh-CHUC** [comment] 2024-06-13 09:54
@ianyh is there anything we could do to help you? (iirc you don't have access to an intel mac), like send some logs etc.
thanks a lot in advance!!!

**Comment by mpepping** [comment] 2024-06-24 12:56
After an uninstall/install of Amethyst 0.21.1 (111), the 'Swap focused window clockwise' (<kbd>Ctrl</kbd>+<kbd>Option</kbd>+<kbd>Shift</kbd>+<kbd>k</kbd> ) worked OK, right after launching Amethyst for the first time. 
However, it broke again after doing 'Relaunch Amethyst' from the menubar.

Sonoma 14.5 (23F79) on M2

**EDIT**: Things started to work for me after (quit Amethyst and) deleting `/Users/martijn/Library/Preferences/com.amethyst.Amethyst.plist` and launching Amethyst again.

**Comment by ipstone** [comment] 2024-06-26 14:53
> Same issue here. I can't throw windows.
> 
> * Amethyst 0.21.1 (111) Installed via Hombrew
> * Intel Mac (16-inch, 2019)
> * macOS Sonoma (14.5)

same issue here, but only happens when throwing windows to a different numbered space on the same monitor ( intel mac, 14.5). My m1 macs don't have this issue on Sonoma 14.5.

**Comment by sw-tracker** [comment] 2024-07-22 10:32
+1

Apple M2 Pro
macOS Sonoma 14.5
Using 1 external curved monitor

**Comment by aystic** [comment] 2024-08-04 14:35
Started having this issue after I updated my MacOS Ventura to 13.6.8 on a 16" Macbook pro M1 Pro. Tried reinstalling Amethyst from the GitHub releases as well as homebrew. Having issues with both.

**Comment by fvcci** [comment] 2024-09-23 14:30
same issue with me

**Comment by ianyh** [comment] 2024-09-28 16:53
See https://github.com/ianyh/Amethyst/discussions/1682

**Closed as not planned by ianyh** 2024-09-28 16:53 UTC
