### ISSUE TITLE
Unable to select floating applications (i.e. Stickies)

### ISSUE THREAD

**Issue by brandonkal** [ianyh/Amethyst#950] opened 2020-02-18 02:43 UTC
**Describe the bug**
The Select from applications... options never returns anything. For instance, I would like to select Stickes as well as some others.

**Applications:**
Stickies

**To Reproduce**
Self explanatory.

**Expected behavior**
It functions.

**Versions:**
 - macOS: 10.13.6
 - Amethyst: 0.14.4

**Comment by brandonkal** [comment] 2020-02-18 02:47
Furthermore, setting Application Bundle ID is broken as well.

I can get the box to display, but after entering "com.apple.Stickies" it freezes and the Add button does not close the pop-up.

**Comment by ianyh** [comment] 2020-02-18 03:06
Duplicate of #935. You need to update.

**Closed by ianyh** 2020-02-18 03:06 UTC
