### ISSUE TITLE
hiding certain apps doesn't trigger a layout

### ISSUE THREAD

**Issue by johnpryan** [ianyh/Amethyst#546] opened 2017-02-02 20:27 UTC
Some apps on OSX don't seem to work very well with Amethyst:

1. launch amethyst
2. launch Chrome
3. launch Slack
4. launch Sublime Text
5. Cmd+tab to focus on Slack
5. Press Cmd+H
6. observe that Slack is hidden, but Amethyst didn't re-layout the windows

Chrome invariably works, so this might not be an amethyst bug...

[Trello Card](https://trello.com/c/sodMLZFk/259-amethyst-hiding-certain-apps-doesn-t-trigger-a-layout)

**Comment by ianyh** [comment] 2017-02-02 20:58
Something something Electron. Might be something strange about how it's dealing with windows.

**Comment by johnpryan** [comment] 2017-02-02 21:04
WebStorm also has this issue, which doesn't surprise me too much either; it's window management on OS X is bizarre.

**Comment by ianyh** [comment] 2017-11-12 19:23
Duplicate of #575

**Closed by ianyh** 2017-11-12 19:23 UTC
Labels: bug
