### ISSUE TITLE
Relayout on hide

### ISSUE THREAD

**Issue by Noitidart** [ianyh/Amethyst#575] opened 2017-04-22 10:08 UTC
I have two windows open and unmaximized VSCode and Firefox. Amethst will make them side by side. When I do Command + M to minimize one window, it is not focusing the other window. If I do Command + H it does hide the window and focus goes to firefox, however relayout does not take place.

1. Can you please help me to make it so on hide, it does re-layout.
2. Or if you can help me to make Command + M to switch app focus after minimization.

Ideally I would love if Command + M swithced app focus, and if a Command + Tab would unminimize, but it seems Command + Tab doesnt do that to a minimized window. 

[Trello Card](https://trello.com/c/NngvMXLk/271-amethyst-on-minimize-focus-next-window-app-or-relayout-on-hide)

**Comment by ianyh** [comment] 2017-04-22 19:12
This might be a duplicate of #475, though I'm not sure why it wouldn't trigger a reflow.

**Comment by ianyh** [comment] 2017-08-23 22:50
@Noitidart 0.11.4 was just released which should fix this. Please reopen if it is still reproduceable.

**Comment by Noitidart** [comment] 2017-08-23 23:01
Thank you sir!

**Comment by HarrisonB** [comment] 2017-10-05 23:07
I'm still experiencing this on 0.11.4, with Chrome + iTerm open.

**Comment by ifreecarve** [comment] 2017-11-17 13:09
I can confirm this behavior as well.  What I also notice is that when the window is restored from the tray, Amethyst may not notice it and as a result not make a frame for it.

**Comment by ifreecarve** [comment] 2017-11-17 13:23
I was able to get window hide events to cause reflows by observing `kAXApplicationHiddenNotification`, but (1) this only handles hides on the current display, not all displays where application windows might be, and (2) the corresponding `kAXApplicationShownNotification` does not seem to fire at all.

**Comment by ifreecarve** [comment] 2017-11-17 14:01
I've added #662 to track this problem

**Closed** 2018-03-29 13:51 UTC
Labels: bug, help wanted, starter issue
