### ISSUE TITLE
Delay missing in 'Focus follows mouse'

### ISSUE THREAD

**Issue by freebrowser1** [ianyh/Amethyst#1222] opened 2022-03-24 06:53 UTC
**Describe the bug**
When enabling this option and moving the mouse over another window, it *immediately* grabs the focus. 
Particularly when typing text and moving the mouse just off window while typing text is very annoying.
Or starting another app does not get focus as the current mouse position is outside the app just started and the user has no time to move the mouse towards it.
A user configurable delay should be very welcome, like Ubuntu does it, or the Autoraise app for macOS.
https://github.com/lhaeger/AutoRaise

**Applications:**
All

**To Reproduce**
Move the mouse just out of current window and the user has no time to move the mouse 

**Expected behavior**
A user configurable delay (e.g. 1/2 - 1 sec) after moving the mouse before the window under the mouse grabs focus/

**Screenshots**

This is how it works in Ubuntu:

![Screenshot-2022-03-24-at-07 47 54](https://user-images.githubusercontent.com/26625141/159859001-6481c9a1-2266-42d8-82bc-3ce97ea59e22.jpg)

**Versions:**
 - macOS: 10.17.2 Monterey
 - Amethyst: 0.15.6
 
**Debug Info**
````
Version: 0.15.6 (93)

OS version: Version 12.2.1 (Build 21D62)

Screens:
	(0.0, 0.0, 1920.0, 1080.0) [(0.0, 0.0, 1920.0, 1080.0)]
	(-1280.0, 280.0, 1280.0, 800.0) [(-1280.0, 0.0, 1280.0, 800.0)]

Configuration:
debug-layout-info: 0
enables-layout-hud: 1
use-canary-build: 0
ignore-menu-bar: 0
float-small-windows: 1
layouts: (
    fullscreen
)
restore-layouts-on-launch: 1
screen-padding-right: 0
screen-padding-top: 0
window-minimum-height: 800
follow-space-thrown-windows: 1
window-resize-step: 5
floating: (
        {
        id = "com.realvnc.vncviewer";
        "window-titles" =         (
        );
    },
        {
        id = "com.apple.Terminal";
        "window-titles" =         (
        );
    }
)
window-margin-size: 0
enables-layout-hud-on-space-change: 1
mouse-follows-focus: 0
mod1: (
    option,
    shift
)
mod2: (
    option,
    shift,
    control
)
window-minimum-width: 1280
new-windows-to-main: 0
floating-is-blacklist: 1
screen-padding-left: 0
window-margins: 0
focus-follows-mouse: 1
screen-padding-bottom: 0
````

**Additional context**

**Comment by cybardev** [comment] 2022-03-27 06:02
This is indeed important, and a simple example is this:

If "Focus Follows Mouse" is enabled and you have a window open (I tried it using BSP layout), I cannot use the mouse to click on Amethyst's own Preferences menu from the top bar. The moment I try to move the cursor out of the top bar and into the popup menu, the window underneath it "steals" the focus, and I can't get into Amethyst Preferences.

**Comment by ianyh** [comment] 2022-07-02 02:59
Duplicate of #638

**Closed as not planned by ianyh** 2022-07-02 02:59 UTC
Labels: duplicate
