### ISSUE TITLE
Feature Request: Highlight Current Window (window border)

### ISSUE THREAD

**Issue by krshrimali** [ianyh/Amethyst#1411] opened 2023-02-07 05:21 UTC
**Is your feature request related to a problem? Please describe.**

- Generally, it's difficult to figure out where my focus is while moving between windows using the keyboard.

**Describe the solution you'd like**

- Probably a window border (optional) around the current window will be very helpful.

**Describe alternatives you've considered**

- There is something similar: [Honer.app](https://github.com/puffnfresh/Honer.app) that I found, but it bugs out when the windows are resized/moved/added using Amethyst. So probably an in-house solution will be great for this.

**Additional context**
[PopOS shell](https://github.com/pop-os/shell) has a very nice feature implementation for this.

**Comment by ianyh** [comment] 2023-02-09 12:41
Duplicate of #127

**Closed as not planned** 2023-02-09 12:41 UTC
Labels: enhancement
