### ISSUE TITLE
Glitch when open TimeMachine.APP

### ISSUE THREAD

**Issue by Naka030** [ianyh/Amethyst#764] opened 2018-11-16 10:58 UTC
## Hackintosh

 - **Amethyst version 0.12.0**:
 - **macOS version 10.14**:
It will resize the UI of TimeMachine.app because of the finder.

**Comment by ianyh** [comment] 2018-11-23 17:19
Duplicate of #274

**Closed by ianyh** 2018-11-23 17:19 UTC
