### ISSUE TITLE
focused window resets after changing screen

### ISSUE THREAD

**Issue by simon-weber** [ianyh/Amethyst#86] opened 2013-11-11 19:05 UTC
If I open two windows on screen 1, focus the non-main one, switch to screen 2, then switch back to screen 1, the main window will be focused.

Is this intended? I don't have an xmonad environment setup at work, but I'm pretty sure it doesn't reset focus after you switch screens.

[Trello Card](https://trello.com/c/H2OdueMK/31-amethyst-focused-window-resets-after-changing-screen)

**Comment by ianyh** [comment] 2015-10-07 20:14
This appears to be a duplicate of #245 now, and that issue is better documented. Going to close this.

**Closed by ianyh** 2015-10-07 20:14 UTC
Labels: enhancement

**Comment by ianyh** [comment] 2015-10-07 20:16
Sorry, I think I mean duplicate of #117
