### ISSUE TITLE
Focused Window Highlighting

### ISSUE THREAD

**Issue by Sp4ssT63r** [ianyh/Amethyst#1102] opened 2021-02-23 08:29 UTC
On a big screen or multi monitor setup, I sometimes loose track which window is currently focused.

Maybe a function like  [Window Focues App](https://fiplab.com/apps/window-focus-for-mac) can be integrated into Amethyst. Maybe the dimming of inactive windows can fade out after the focused window changed to only help shortly after the focus changed. It would be nice if the fade out interval and the dimming color could be chosen by the user.

I currently use limelight for this, but a neat looking solution integrated into amethyst would be preferable.
![Screen Shot 2021-02-23 at 09 25 37](https://user-images.githubusercontent.com/28724730/108818355-870b5b00-75b9-11eb-8a48-106f7830edf7.png)

**Comment by mrseoliveira** [comment] 2021-03-19 12:56
Use hazeover app, it highlights your focused window

**Comment by vnckppl** [comment] 2021-03-23 15:41
I use limelight for this: https://github.com/koekeishiya/limelight

**Comment by ianyh** [comment] 2021-07-03 01:43
Duplicate of #127

**Closed as completed by ianyh** 2021-07-03 01:43 UTC
Labels: duplicate, enhancement
