### ISSUE TITLE
Expand Config Example 

### ISSUE THREAD

**Issue by Indyandie** [ianyh/Amethyst#1384] opened 2023-01-21 21:42 UTC
Include all configuration options in [.amethyst.sample.yml](https://github.com/ianyh/Amethyst/blob/development/.amethyst.sample.yml).
- Configuration Keys
- Command Keys
- Shortcuts (Not sure if this is supported at the moment.)

**Comment by ianyh** [comment] 2023-01-21 22:05
Duplicate of #1321

**Closed as not planned by ianyh** 2023-01-21 22:05 UTC
Labels: duplicate

**Comment by Indyandie** [comment] 2023-01-21 22:20
Apologies @ianyh! :sweat_smile: I should've checked before submitting a new ticket. Does the config file support shortcuts?

**Comment by ianyh** [comment] 2023-01-21 22:22
No worries! Yes, it should. There was a bug in 0.16.0 that broke them, but it should be fixed in 0.16.1.

**Comment by Indyandie** [comment] 2023-01-22 22:08
Is this the correct format for shortcuts?

```yml
# switch to the two-pane layout
two-pane:
  mod: mod1
  key: s
```

**Comment by jabkoo** [comment] 2023-02-03 20:35
@Indyandie I was trying to discover it too and I found this example in [Amethyst/default.amethyst](https://github.com/ianyh/Amethyst/blob/bfae0c3e769313fec1e4e0cc249b27e5e1d5fe75/Amethyst/default.amethyst) file:

```
"select-wide-layout": {
    "mod": "mod1",
    "key": "s"
}
```

So you can do the same in YAML file for Two Pane layout with:
```
select-two-pane-layout:
    mod: mod1
    key: s
```

**Comment by Indyandie** [comment] 2023-02-03 21:14
@jabkoo  Thank so much! I'll give this a try as soon as I get a chance.

**Comment by Indyandie** [comment] 2023-02-12 04:30
@jabkoo that's the right format!

But for some reason I couldn't set **two pane** to select using the `s` key. What is more puzzling, is that `s` key works with the **tall** layout but `t` key didn't. 😵 

I ended up using number keys to select the layouts that I wanted.

```yml
select-two-pane-layout:
  mod: mod1
  key: "2"

select-fullscreen-layout:
  mod: mod1
  key: "7"

select-tall-layout:
  mod: mod1
  key: "8"
``

**Comment by ianyh** [comment] 2023-02-12 04:36
mod1+s appears to be the default command for select-wide-layout. That is probably colliding with it. The config file parsing should probably be changed to override it, though.

**Comment by Indyandie** [comment] 2023-02-12 04:41
That also explains why `mod1+t` didn't work either since the default is toggle float.

**Comment by ianyh** [comment] 2023-02-12 04:45
Could you actually open a new issue to track that?
