### ISSUE TITLE
mod2 + [n] doesn't work between two displays

### ISSUE THREAD

**Issue by HerrSpace** [ianyh/Amethyst#763] opened 2018-11-10 18:35 UTC
Thanks for amethyst, it makes macos much more usable for me.

## System

 - **Amethyst version**:
Tested on the last stable as well as the current dev build 0.12.2b3 

 - **macOS version**:
10.14.1

## What's the problem?
My problem is that this shortcut:
`mod2 + [n]` - move focused window to nth spaces.
doesn't work when the source workspace and the destination workspace are on different displays. If so using this shortcut causes the following:
- The destination display switches to the correct destination workspace
- The cursor temporarily moves to the windows decoration of the window to be moved
- The window to be moved disappears
- The destination monitor becomes the active one (no longer dimmed menu bar) for a bit under a second
- The window re-appears on the source workspace and the cursor moves back to where it was.

When I try to move the window to the same destination workspace twice, everything is the same except that the window doesn't disappear for a moment. The cursor still takes a second to go back to it's original location though.

I do have enabled the `Switch to Desktop n` shortcuts in the macos settings but maybe I have inadvertently overwritten some other crucial shortcuts? 

## What applications are involved?
Tested with firefox, slack, spotify..

**Comment by ianyh** [comment] 2018-11-14 14:42
This is a duplicate of #121, but as this is using the new reporting format I'm going to keep this one.

**Comment by ianyh** [comment] 2019-04-06 16:24
I think #817 actually fixes this.

**Closed by ianyh** 2019-04-06 16:24 UTC
Labels: bug

**Comment by HerrSpace** [comment] 2019-04-16 14:46
Seems to be fixed, thanks!
