### ISSUE TITLE
Opera URL Bar laid out like a full window

### ISSUE THREAD

**Issue by pgebheim** [ianyh/Amethyst#666] opened 2017-11-26 05:46 UTC
## System

 - **Amethyst version**: 0.11.4 (52)
 - **macOS version**: 10.12.16

## What's the problem?

When typing in the Opera's URL bar, the autocomplete window is treated as a full window (not a small window) and is resized into the window tree.

## How can it be reproduced?

Type within URL into Opera's URL bar.

## What applications are involved?

Opera  (v.49)

## Has anything fixed it, even temporarily?

The only fix is to list opera as a floating application

## dotfile (if you have one)

```
{

}
```

## Screenshots

<img width="480" alt="screenshot at nov 25 20-49-33" src="https://user-images.githubusercontent.com/86010/33237509-119be26c-d22a-11e7-963d-b9f7441c8bf0.png">

**Comment by pgebheim** [comment] 2017-11-26 05:53
https://github.com/ianyh/Amethyst/blob/4cda1093d0eb5a9f16d9d175182e5d05bd2a3c37/Amethyst/Categories/SIWindow%2BAmethyst.swift#L170

Looks like this heuristic isn't quite enough here.

**Comment by ianyh** [comment] 2018-01-16 14:14
Duplicate of #308, but you are correct that the simple heuristic isn't quite enough in many applications.

**Closed by ianyh** 2018-01-16 14:14 UTC
