### ISSUE TITLE
Occasional sluggish layout re-arrangement with Chrome

### ISSUE THREAD

**Issue by macintacos** [ianyh/Amethyst#1257] opened 2022-06-10 17:29 UTC
**Describe the bug**

I don't think that a description will do this justice, so I'll show a screen recording.

https://user-images.githubusercontent.com/8128941/173117608-901ece3c-bffd-455e-94a1-0156cf3bc4a9.mp4

You'll see that, when switching between layouts, the transitions are not instant, and I have to hit the layout key multiple times for things to look "correct".

This sluggishness also seems to happen when moving windows around inside of a layout:

https://user-images.githubusercontent.com/8128941/173117931-1375d224-dbfa-4cd1-a009-bb1732d83c5f.mp4

Typically, when I start Amethyst for the day, the animations for things like this are instant. But at some point (still trying to figure out what causes it) this sluggishness happens and it's pretty frustrating. Sometimes relaunching Amethyst fixes it, sometimes it doesn't. Often it can be "fixed" for a short amount of time if I reboot my machine, but it seems to always come back.

To make this even stranger, this has only been happening for a couple of weeks, and I've been using Amethyst for a few months with no issues. There has not been an update to Amethyst in this time that I can blame this behavior on. The only thing I can think of is that I tried Yabai for a short period of time last week (disabled Amethyst during that time) but I have since gotten rid of that and got back to Amethyst. I unfortunately don't remember if this behavior started before or after I installed Yabai. It feels weird to place the blame on that though, considering that it's been removed from my system, but it's 

**Applications:**

> What applications are involved?

This seems to happen for every application, not just the app that I used in the screen recording above.

**To Reproduce**

I'm still not sure how I get to this state, but I'll update this message if I have a reliable setup.

**Expected behavior**

Switching between layouts, moving windows around, etc. should be instant, and shouldn't require executing the same command multiple times.

**Versions:**
 - macOS: 12.4 on an M1 Pro MBP
 - Amethyst: 0.15.6
 
**Debug Info**
```
$ /Applications/Amethyst.app/Contents/MacOS/Amethyst --debug-info
Version: 0.15.6 (93)

OS version: Version 12.4 (Build 21F79)

Screens:
	(0.0, 0.0, 1728.0, 1117.0) [(0.0, 0.0, 1728.0, 1117.0)]
	(1728.0, 0.0, 2560.0, 1440.0) [(1728.0, -323.0, 2560.0, 1440.0)]
	(4288.0, 0.0, 2560.0, 1440.0) [(4288.0, -323.0, 2560.0, 1440.0)]

Configuration:
window-minimum-width: 0
floating-is-blacklist: 1
window-margins: 1
mouse-resizes-windows: 1
enables-layout-hud: 1
debug-layout-info: 0
smart-window-margins: 1
window-resize-step: 5
layouts: (
    "two-pane",
    tall,
    fullscreen
)
window-margin-size: 10
mod1: (
    option,
    shift
)
restore-layouts-on-launch: 0
screen-padding-bottom: 10
focus-follows-mouse: 0
follow-space-thrown-windows: 1
new-windows-to-main: 0
enables-layout-hud-on-space-change: 1
use-canary-build: 1
ignore-menu-bar: 0
screen-padding-top: 10
window-minimum-height: 0
mouse-follows-focus: 1
screen-padding-right: 10
mouse-swaps-windows: 1
float-small-windows: 1
mod2: (
    option,
    shift,
    control
)
floating: (
        {
        id = "com.apple.systempreferences";
        "window-titles" =         (
        );
    },
        {
        id = "io.appmakes.Paletro";
        "window-titles" =         (
        );
    },
        {
        id = "com.zsa.wally";
        "window-titles" =         (
        );
    },
        {
        id = "fm.qmk.toolbox";
        "window-titles" =         (
        );
    },
        {
        id = "com.hogbaysoftware.Bike";
        "window-titles" =         (
        );
    }
)
screen-padding-left: 10
```

**Comment by brandonkboswell** [comment] 2022-06-11 13:14
Are you experiencing this when Chrome is not involved? I have also recently started experiencing something like this, but I only seem to experience it when Chrome is one of the windows.

**Comment by macintacos** [comment] 2022-06-13 00:25
Yes! I didn't even think about Chrome being the common link in this to be honest, but now that I'm testing things it seems to be specific to Chrome.

I guess as a workaround I could stop using Chrome until this is resolved, this that's less than ideal 🙂

**Comment by ajorpheus** [comment] 2022-06-13 09:40
@macintacos , @brandonkboswell 

While attempting to troubleshoot an issue with Amethyst not working at all for me (#1240), I built Amethyst locally from the dev branch which has an upgrade to the [Silica](https://github.com/ianyh/Silica/) (see #1250).

I am quite certain I had an issue with layout transition being sluggish when chrome was involved, however I have not noticed that lag with the development build. YMMV.

**Comment by macintacos** [comment] 2022-06-13 21:17
I'm not familiar enough with Xcode development to know how to accomplish that tbh. I ran the setup script and Xcode seems to build fine, but I'm not entirely sure how to build the project such that it spits out an actual "Amethyst" application that I can run outside of Xcode?

**Comment by gaoDean** [comment] 2022-06-14 08:30
Hi, I also get this “sluggishness”, but I never use chrome, only safari

**Comment by ajorpheus** [comment] 2022-06-14 08:55
@macintacos 

> I'm not familiar enough with Xcode development to know how to accomplish that tbh. I ran the setup script, and Xcode seems to build fine, but I'm not entirely sure how to build the project such that it spits out an actual "Amethyst" application that I can run outside of Xcode?

Aaah, I struggled with this as well. The steps are as below.

-----
### Optional Step
0. One thing I would recommend doing is changing the version and building like so before doing the archive so that you can quickly tell if the correct version is running from the drop-down in the menu bar:


![image](https://user-images.githubusercontent.com/1554671/173536910-6c71d80f-641c-49df-9a72-b0b6c989a9c4.png)

which results in this:

![image](https://user-images.githubusercontent.com/1554671/173537074-9eed6001-433c-4af5-b8ce-9b1a90670149.png)

-----
### Steps

1. In Xcode and select Product > Archive. This will create an archive and open an Organizer window with the archive listed.

2. Select an archive that has just been created (look at the 'Creation Date' column to confirm) and click 'Distribute App':
![image](https://user-images.githubusercontent.com/1554671/173535431-5e49b9bb-b328-424b-b7b1-b0e5101ff09b.png)

3. In the next dialogue, select 'Copy App' and then choose the destination:
![image](https://user-images.githubusercontent.com/1554671/173536556-d3334443-ec7c-48ad-bb0d-c27cdb4f9b69.png)

4. Finally, copy the App from the destination in step 3 to /Applications, and you are all set.

5. Remember to clean the Accessibility preferences before starting the app for the first time.

**Comment by brandonkboswell** [comment] 2022-06-14 14:58
Thanks for the steps @ajorpheus. I was able to generate an archive app, but whenever I open it nothings happens. Hopefully @ianyh can issue a new release soon as it seems like the fix may already committed.

**Comment by macintacos** [comment] 2022-06-14 15:00
Was literally about to say the same as @brandonkboswell - I try opening the app and it doesn't seem to do anything. Will hope that there's a fix made available in the main app as well.

**Comment by ajorpheus** [comment] 2022-06-14 20:21
@brandonkboswell , @macintacos 

The app not doing anything might just be macOS' accessibility malarkey at work. May I ask if you remove Amethyst from Accessibility and relaunch it, does it prompt you to enable Accessibility again ?

**Comment by brandonkboswell** [comment] 2022-06-14 20:57
@ajorpheus Unfortunately, I tried that and the app doesn't do anything.

**Comment by Bellavene** [comment] 2022-06-16 12:31
Could you please share the app with animations turned on?
I'll try.

**Comment by ianyh** [comment] 2022-06-18 20:24
Wait, how is that animating the window movements?

**Comment by brandonkboswell** [comment] 2022-06-18 20:28
Unsure, it started about 3 weeks ago and as far as I know didn't align with an Amethyst update or OS update. My theory is it has something to do with a Chrome update.

**Comment by macintacos** [comment] 2022-06-18 20:28
I have no idea, it's a bug. I'm not doing anything custom with Amethyst — I opened this issue because I want it to stop 😅 

It was mentioned earlier in the thread, but it seems like an issue specific to Chrome.

**Comment by brandonkboswell** [comment] 2022-06-19 17:59
@macintacos, @ajorpheus, unfortunately I am still experiencing this on the 16.0 Beta. Are you seeing the same?

**Comment by ajorpheus** [comment] 2022-06-20 08:29
@brandonkboswell 

I just tried 16.0 beta, and the transition is almost instantaneous for me. 

Steps I followed to test the transition:
1. Start with Chrome as the only sole window open.
2. Switch to Two Pane layout, nothing happens, since Chrome is the only window open.
3. Open another Chrome window
4. The windows are immediately arranged to take a vertical half each, of the screen

------

One thing I've had success in the path with to try and figure out if there are any rogue applications interfering with Amethyst is to quit any applications listed under 'Manageable applications' in the output of  `/Applications/Amethyst.app/Contents/MacOS/Amethyst --debug-info --include-apps`

**Comment by ajorpheus** [comment] 2022-06-20 08:41
@ianyh  there are some applications in the output of ` /Applications/Amethyst.app/Contents/MacOS/Amethyst --debug-info --include-apps` which don't have a window, but are treated as manageable, for example:

```
	talagent (com.apple.talagent)
	AppSSOAgent (com.apple.AppSSOAgent)
	storeuid (com.apple.storeuid)
	coreautha (com.apple.LocalAuthentication.UIAgent)
```

Should these be excluded out of the box? I remember seeing an exclude list somewhere in the code earlier, can't find it anymore.

**Comment by illettante** [comment] 2022-06-22 01:26
I've started having this issue recently too, with or without chrome running. When I do a window operation, Amethyst now seems to move windows step-by-step (move to correct side of screen, then move to top, then resize, then move other apps, then resize other apps, and I have to reevaluate windows each step for it to complete the operation.

**Comment by macintacos** [comment] 2022-06-22 01:37
I think I need to leave Amethyst 0.16.0b running for a few more days before I consider this "fixed" on my end, however I installed that version of the application and the issue seems to have gone away for me after a reboot. I don't want to call this fixed yet because in the past it seems like it'll work for a few minutes/hours and then return.

I'll update this by the end of the week with my longer-term results.

**Comment by macintacos** [comment] 2022-06-22 04:23
Sigh, of course, spoke too soon. The same sluggish rearrangement of windows is back, even on the latest beta.

**Comment by brandonkboswell** [comment] 2022-06-22 12:57
Yeah, I ran into it too yesterday. This is probably a placebo, but I felt like I have run into it less frequently. Either that or I'm just getting used to the bug ;(

**Comment by macintacos** [comment] 2022-06-23 17:12
I'm at the point now where I'm probably just going to move away from using Chrome and use Safari instead or something. It's a bummer, but this is really jarring for my workflow. Hope it gets fixed.

**Comment by ianyh** [comment] 2022-06-23 17:22
I've noticed something like this with a game I play, so I can probably look into it that way.

**Comment by Bellavene** [comment] 2022-06-23 17:27
@macintacos Chrome was always cringe. I remember when it first came out. They added an "update manager", which was so deeply hidden in the system and eating CPU time when Chrome was not even running or updating. If you delete Chrome, this little nonsense still was in the system and loading at start. I believe this is still there. Total bollocks. Avoid it if you can. There are a lot of browsers that use Chromium, which does not have that. I personally use Vivaldi and more than happy with it.

**Comment by ianyh** [comment] 2022-06-23 18:15
Please let's not get into arguments about what software should or should not be used. Chrome is an application that people use and Amethyst shouldn't be impeding that.

**Comment by macintacos** [comment] 2022-06-23 18:18
Agree. My comment was not meant to bash Chrome, it was more meant to communicate that this issue is getting to the point where I'm willing to look at alternative applications to "work around" this, so to speak.

**Comment by Bellavene** [comment] 2022-06-23 18:21
I don't care what people use. I am just informing people my personal experience. I don't believe that such behavior is good, as installing a hidden process without asking you, which stays in a hidden place and which eats your system resources, in other words acts as malware.

**Comment by ianyh** [comment] 2022-06-23 20:06
@Bellavene I understand the concern, but it's not yet clear to me what the actual root cause of the issue here is, and this isn't the venue for discussing the merits or demerits of a particular piece of software.

**Comment by Bellavene** [comment] 2022-06-23 20:28
@ianyh That is true. Sorry for commenting unrelated message. That type of experience is just hard to forget.

**Comment by asmvik** [comment] 2022-06-23 21:53
@ianyh This issue is caused by an undocumented accessibility property `AXEnhancedUserInterface`

**Comment by Bellavene** [comment] 2022-06-25 22:42
Tested a bit and found that this bug only appear when “Displays have separate Spaces” is off. Otherwise, works as expected.

**Comment by macintacos** [comment] 2022-06-27 15:55
Turning that off seems to have done the trick for me, which is an acceptable workaround in my case (I don't use Spaces anyway). Still hope that this can be fixed!

**Comment by brandonkboswell** [comment] 2022-06-27 17:17
On initial inspection, this also seems to fix this and a few other bugs I've been experiencing. I will gladly give up spaces to have my old Amethyst behavior back.

**Comment by ianyh** [comment] 2022-06-27 18:19
> @ianyh This issue is caused by an undocumented accessibility property `AXEnhancedUserInterface`

Thanks. I'll look at how you're handling it with yabai when I get a chance.

**Comment by illettante** [comment] 2022-06-29 03:47
the FOSS community in action, i love to see it

**Comment by Bellavene** [comment] 2022-07-17 01:38
Some applications are forcing that bug, like shortcat and e.g.

**Comment by auscompgeek** [comment] 2022-07-18 04:59
FWIW [Rectangle](https://github.com/rxhanson/Rectangle) also [handles `AXEnhancedUserInterface`](https://github.com/rxhanson/Rectangle/blob/master/Rectangle/AccessibilityElement.swift)

**Comment by illettante** [comment] 2022-08-03 04:25
I don't know about anyone else, but this issue appears to have inexplicably resolved itself for me as of a couple of days ago. Can provide no useful information on this unexpected but excellent thing

**Comment by tobernguyen** [comment] 2022-08-08 16:14
> Tested a bit and found that this bug only appear when “Displays have separate Spaces” is off. Otherwise, works as expected.

Tried turning off `Displays have separate Spaces` but it doesn't fix the problem for me.

**Comment by Bellavene** [comment] 2022-08-09 22:46
> > Tested a bit and found that this bug only appear when “Displays have separate Spaces” is off. Otherwise, works as expected.
> 
> Tried turning off `Displays have separate Spaces` but it doesn't fix the problem for me.

Then you have some sort of app that interferes. Have seen some strange behavior with some apps. Try to find which one.

**Comment by dncc89** [comment] 2022-08-14 12:15
Adding shortcat to floating app list fixed the issue for me. Vimac/homerow are still causing interference.

**Closed as completed** 2023-01-29 17:45 UTC
Labels: bug

**Comment by sspaeti** [comment] 2023-02-10 14:30
Unfortunately, this issue persists for a very long time. It's not only Chrome/Brave but also the most severe. I'm using one external monitor and spaces on both monitors. Unfortunately, I'll have to try alternatives now.
