### ISSUE TITLE
Move focused window to next/previous workspace

### ISSUE THREAD

**Issue by metalseargolid** [ianyh/Amethyst#338] opened 2015-10-22 18:20 UTC
One of the nice features that made me look at Amethyst in the first place was the ability to use Control + Option + Shift + *SpaceNum* to move the currently focused window to the *SpaceNum* workspace. I'd like to request to add a similar feature but move the focused window to the next or previous workspace, similar to switching workspaces using Control + Right/Left.

[Trello Card](https://trello.com/c/Du4BlLZj/166-amethyst-move-focused-window-to-next-previous-workspace)

**Comment by ianyh** [comment] 2015-11-12 15:04
Duplicate of #164

**Closed by ianyh** 2015-11-12 15:04 UTC
