### ISSUE TITLE
Not adjusting at once

### ISSUE THREAD

**Issue by sleepymalc** [ianyh/Amethyst#1389] opened 2023-01-23 21:11 UTC
**Describe the bug**
Using fullscreen mode for applications like chrome, and VSCode, the windows do not re-size at once; rather, it resizes *gradually*, and I will need to manually evoke re-evaluate shortcut to force it to re-adjust.

**Applications:**
Chrome, VSCode, etc.

**To Reproduce**
Get in fullscreen mode, mess up the window size, and then evoke readjust.

**Expected behavior**
Windows should be readjusted at once.

**Screenshots**
https://user-images.githubusercontent.com/60427058/214150822-747fefe4-36e9-4ca5-b106-9a6db291bfe8.mov

**Versions:**
 - macOS: Ventura 13.1
 - Amethyst: 0.16.1
 
**Debug Info**
```
$ /Applications/Amethyst.app/Contents/MacOS/Amethyst --debug-info [--include-apps]

Version: 0.16.1 (95)

OS version: Version 13.1 (Build 22C65)

Screens:
	(0.0, 0.0, 2560.0, 1440.0) [(0.0, 0.0, 2560.0, 1440.0)]
	(-1728.0, 129.0, 1728.0, 1117.0) [(-1728.0, 194.0, 1728.0, 1117.0)]
	(2560.0, -790.0, 1440.0, 2560.0) [(2560.0, -330.0, 1440.0, 2560.0)]

Configuration:
follow-space-thrown-windows: 1
floating: (
        {
        id = "org.yanex.marta";
        "window-titles" =         (
        );
    },
        {
        id = "com.apple.finder";
        "window-titles" =         (
        );
    },
        {
        id = "org.inkscape.Inkscape";
        "window-titles" =         (
        );
    },
        {
        id = "com.apple.systempreferences";
        "window-titles" =         (
        );
    },
        {
        id = "com.torusknot.SourceTreeNotMAS";
        "window-titles" =         (
        );
    },
        {
        id = "com.runningwithcrayons.Alfred";
        "window-titles" =         (
        );
    },
        {
        id = "com.apple.calculator";
        "window-titles" =         (
        );
    },
        {
        id = "com.aone.keka";
        "window-titles" =         (
        );
    },
        {
        id = "com.macpaw.zh.CleanMyMac4";
        "window-titles" =         (
        );
    },
        {
        id = "org.pqrs.Karabiner-EventViewer";
        "window-titles" =         (
        );
    }
)
restore-layouts-on-launch: 1
window-resize-step: 5
screen-padding-bottom: 0
enables-layout-hud-on-space-change: 0
float-small-windows: 0
ignore-menu-bar: 0
focus-follows-mouse: 0
window-minimum-width: 0
mod2: (
    option,
    shift,
    control
)
screen-padding-top: 0
layouts: (
    fullscreen,
    tall,
    "two-pane"
)
floating-is-blacklist: 1
new-windows-to-main: 0
mouse-resizes-windows: 0
enables-layout-hud: 1
debug-layout-info: 0
smart-window-margins: 0
screen-padding-left: 0
mouse-swaps-windows: 0
use-canary-build: 0
mouse-follows-focus: 1
window-margin-size: 10
window-minimum-height: 0
screen-padding-right: 0
mod1: (
    option,
    shift
)
window-margins: 1
```
Note: `--include-apps` will list your manageable applications, but is optional if you don't want to list that.

**Additional context**
N/A.

**Comment by mspoehr** [comment] 2023-01-25 17:44
I'm having a similar issue when unfullscreening windows. Except for me, Amethyst just ignores the unfullscreened window and I need to close and reopen the window it to get it to resize (pressing the force resize shortcut many times does nothing, in contrast to the above video).

Debug info:

```
Version: 0.16.1 (95)

OS version: Version 12.6.2 (Build 21G320)

Screens:
	(0.0, 0.0, 1792.0, 1120.0) [(0.0, 0.0, 1792.0, 1120.0)]
	(2504.0, 554.0, 1440.0, 2560.0) [(2504.0, -1994.0, 1440.0, 2560.0)]
	(-856.0, 1120.0, 3360.0, 1890.0) [(-856.0, -1890.0, 3360.0, 1890.0)]

Configuration:
enables-layout-hud-on-space-change: 1
follow-space-thrown-windows: 1
float-small-windows: 1
screen-padding-left: 0
screen-padding-bottom: 0
ignore-menu-bar: 0
window-resize-step: 5
restore-layouts-on-launch: 1
mod1: (
    option,
    shift,
    command
)
window-minimum-width: 0
screen-padding-top: 0
use-canary-build: 0
window-minimum-height: 0
floating-is-blacklist: 1
window-margin-size: 0
debug-layout-info: 0
enables-layout-hud: 1
mouse-follows-focus: 0
layouts: (
    tall,
    fullscreen,
    wide,
    column
)
window-margins: 0
floating: (
    "com.1password.1password",
    "com.microsoft.Outlook",
    "com.apple.finder",
    "com.apple.calculator"
)
mod2: (
    option,
    shift,
    control,
    command
)
new-windows-to-main: 0
screen-padding-right: 0
focus-follows-mouse: 0
```

**Comment by ianyh** [comment] 2023-01-28 21:51
I can't seem to load that screen recording, but I expect this is a duplicate of #1257.

**Closed as not planned** 2023-01-28 21:53 UTC
Labels: bug, duplicate
