### ISSUE TITLE
Opera Floating Windows Problem

### ISSUE THREAD

**Issue by daphen** [ianyh/Amethyst#599] opened 2017-05-28 13:02 UTC
Hey, I use Opera Developer Edition and whenever I type in the address bar Amethyst changes my layout and then changes back again when I press enter. Thoughts?

This is super interesting. It appears the problem only appears if opera is on my external monitor.

Right, it's because Opera opens another window to make searching straight to Google through the address bar possible. Man, I wonder how I'm going to get around this.

Edit:
Oh, "Float small Windows" and then adding Opera fixed the problem.
You can close this but I think it's fair to not delete it since someone else might run into the same problem.

Edit: When selecting Float Small Windows targeting Opera, it seems Opera isn't monitored by the app at all anymore, so windows float on top of it etc.
So no, it's not working. I'm pretty sure it worked when I first turned it on but then stopped working. I've restarted like five times but ended up with having to remove the floating windows thing.

Ugh, this is SO annoying..

**Comment by ianyh** [comment] 2017-07-03 19:15
This may be a duplicate of #308

**Comment by daphen** [comment] 2017-07-03 21:39
@ianyh Yeah, you're right, it is.

**Closed** 2017-07-03 21:40 UTC
Labels: bug, duplicate
