### ISSUE TITLE
Ublock chrome extension turns Amethyst into a mouse trap

### ISSUE THREAD

**Issue by constructorNo1** [ianyh/Amethyst#563] opened 2017-03-24 00:14 UTC
While being absolutely stoked about the awesomeness Amethyst is, I believe I discovered a defect with popups created by Chrome extensions.

Specifically, when my Chrome ( 57.0.2987.110 (64-bit) ) has ublock matrix installed, when I click on it, ublock creates a popup close to the menu bar, but it seems 

* Amethyst (0.11.1 but just upgraded to 0.11.2 (45) and still have the problem) thinks the window got created in the middle of the screen
* moves the mouse there (mouse follows focus is enabled)
* (most annoying) the mouse is constrained to stay in this imaginary invisible small window (mouse trap) in the middle of the screen. 

One can reload the current page, which seems to free the mouse; one can move the mouse really really fast and trick it to leave the mouse trap, after which all is good again.

I'll be happy to help debug further.

[Trello Card](https://trello.com/c/9xOQK7z7/264-amethyst-ublock-chrome-extension-turns-amethyst-into-a-mouse-trap)

**Comment by ianyh** [comment] 2017-03-30 16:29
That's super weird. Do you have focus follows mouse enabled as well? How does ublock matrix work?

**Comment by klapauciusisgreat** [comment] 2017-04-09 18:36
Yes, I have enabled focus follows mouse.

THere are actually a number of unrelated issues i think.

1) the mouse trap behaviour happens when both FFM (focus follows mouse) AND mouse follows focus (MMF) are active.

2) Once FFM is active, then the popup window from chrome extensions also close one I move the mouse - I think this is because the mouse is actually not positioned inside the window, but the popup window expects it. (I actually don't know what's going on behind the curtain, just thought it would be good to report since it's a bit of an annoyance to anyone using a chrome extensions that has popup dialoges).

If it helps I can send a short screencast in personal mail, but it's pretty easy to install ublock matrix and see for yourself - https://chrome.google.com/webstore/detail/umatrix/ogfcmafjalglgifnmanfmnieipoejdcf

**Comment by trey-pindrop** [comment] 2017-08-07 20:27
This isn't solely a Ublock extension problem, it's any Chrome/Chromium extension popup menu which triggers the problem.  I was able to trigger it on the LastPass extension.

With both FFM and MMF enabled, at first it seems #337 is resolved, I can move the mouse over most of the menu.  But shortly after I move the mouse to the bottom of the popup menu the mouse cursor gets trapped in a small area in the center of the Chrome/Chromium window.  The only way I got out of it was a Keyboard Maestro macro which gives iTerm2 focus (and moves the mouse cursor to its center).  

I don't have a use case for MMF, but FFM is the Holy Grail of how I'd like to interact with this Mac.  It feels almost there.

**Comment by klapauciusisgreat** [comment] 2017-08-26 17:34
Agreed that this is an Chrome problem, not ublock specific. A lot of other extensions have this problem, and also some popup windows (e.g., the copy status window when transferring files in the finder, or the Google Hangouts app). Anyway, for the most part, I'm putting up with the annoyance to have the tiling WM support. I can't imagine going back to the stock mac VM.

**Comment by trey-pindrop** [comment] 2018-03-16 18:33
Any traction on this?  FFM enabled on 0.12.0 released recently has the same issue.  I didn't see this issue as resolved in the release notes, but I dutifully try every time there's a new release.

A workable FFM would give me computing Nirvana on this Mac.  I understand it's a very intractable problem, due to some Apple design decision that goes back to 1984.  FFM in Amethyst gets 95 percent of the way there, as is.

**Comment by trey-pindrop** [comment] 2018-03-16 18:40
If I turn off Mouse Follows Focus (MFF), I can operate Chrome extension windows.  There is a catch, though:  I have to move the mouse over the menu pretty quickly, *BEFORE* it displays.  Otherwise the menu detects it does not have focus and then it disappears immediately.  Fairly annoying, but not impossible to operate.

This is with 0.12.0 installed, just now.

**Comment by ianyh** [comment] 2018-03-16 20:19
Yeah, it's still an open issue. The next release should come with some focus-follows-mouse improvements, though. There's also some CPU-usage issues with it.

**Comment by trey-pindrop** [comment] 2018-08-13 18:45
The next release has come, and still no fix for this issue.  It looks like there are a number of open issues regarding FFM and popup menus.  

I've filed #739 to give Amethyst a configurable keyboard shortcut for experimental features.  I can use Keyboard Maestro to turn off FFM when Chrome/Chromium have focus, and turn it back on when something else gets focus.  It'll be a real hack, but something to tide me over until the root cause of this problem is dealt with.

**Comment by ianyh** [comment] 2018-08-26 18:06
I think this can be done when #740 lands in production.

**Closed by ianyh** 2018-08-26 18:06 UTC
Labels: bug
