### ISSUE TITLE
Enhancement Middle-Wide Layout

### ISSUE THREAD

**Issue by jorgelaranjo** [ianyh/Amethyst#702] opened 2018-04-03 12:57 UTC
## System

 - **Amethyst version**: 0.12.0(57)
 - **macOS version**: 10.13.3

# Enhancement
Would it be possible to make the `middle-wide` layout always put the window on the middle and create those two other `columns` left and right automatically, as empty space?
This is specially important when working with wide and ultra wide monitors, I'd say.

Happy to help change that part of code to allow for a new `middle-middle layout`

Possibly making this particular one always return >2 ?

`let secondaryPaneCount = round(Double(windows.count - 1) / 2.0)`

**Comment by ianyh** [comment] 2018-08-10 22:48
Duplicate of #83

**Closed by ianyh** 2018-08-10 22:48 UTC
Labels: enhancement, layout
