### ISSUE TITLE
Regex in floating window titles

### ISSUE THREAD

**Issue by unexist** [ianyh/Amethyst#1104] opened 2021-03-04 07:09 UTC
I am currently trying to configure floating windows and it doesn't look like the title string can be a regex?

So either it lacks the proper documentation/I am unable to find or I'd like to request a way to specify a regex that is used to match floating windows. :)

**Comment by ianyh** [comment] 2021-07-03 01:45
Duplicate of #981.

**Closed as completed by ianyh** 2021-07-03 01:45 UTC
Labels: duplicate, enhancement
