### ISSUE TITLE
Chrome toolbar buttons with popover don't work

### ISSUE THREAD

**Issue by snario** [ianyh/Amethyst#277] opened 2015-01-15 11:56 UTC
If you have an extension on Chrome, say for example Gmail Checker, and you click on the button in the toolbar which should launch a tooltip / popover to show your email, the pane will open but as soon as your mouse moves it instantly closes.

[Trello Card](https://trello.com/c/R5RKH7Z6/114-amethyst-chrome-toolbar-buttons-with-popover-don-t-work)

**Comment by raizyr** [comment] 2016-03-10 16:59
This appears to be related to Focus follows mouse.  I can duplicate with Amethyst 0.9.10 (32) and Chrome  49.0.2623.87 with Focus follows mouse turned on.  If you are very quick you can sometimes move the mouse to focus on the popover, but it is difficult.  Turning off Focus follows mouse allows access to the popovers as normal with no speed mousing needed.

**Comment by raizyr** [comment] 2016-03-10 17:02
I just tried Amethyst 0.10b2 (34) and was able to duplicate the same behavior with Focus follows mouse.

**Comment by 0x62** [comment] 2016-05-31 15:52
+1

Appears that this could be resolved by adding a check to return without focusing if the window already has focus at [FocusFollowsMouseManager.swift#L50](https://github.com/ianyh/Amethyst/blob/9b211b161fd457acc3eb0392b156500aa32f5128/Amethyst/Managers/FocusFollowsMouseManager.swift#L50). However, I don't know enough about Swift to implement it myself.

**Comment by ianyh** [comment] 2017-11-12 19:06
Duplicate of #563

**Closed by ianyh** 2017-11-12 19:06 UTC
Labels: bug
