### ISSUE TITLE
Can't Add Apps to Black/Whitelist

### ISSUE THREAD

**Issue by marlowe310** [ianyh/Amethyst#777] opened 2018-12-03 21:48 UTC
Hey just a heads up -- latest update seems to have removed the ability to add an app to the "floating" list (unless I'm just not seeing it). 

Adding windows by title (which is *awesome*) seems to be working as expected though!

**Comment by ianyh** [comment] 2019-02-17 15:35
Going to close this as I think it may have been a point of UI confusion and it hasn't any activity. Feel free to reopen if the issue is still relevant.

**Closed by ianyh** 2019-02-17 15:35 UTC
