### ISSUE TITLE
New Layout Request

### ISSUE THREAD

**Issue by gprimosch** [ianyh/Amethyst#399] opened 2016-02-09 15:51 UTC
I am not sure what to call this layout, so it is easier to visualize with a picture:

![image](https://cloud.githubusercontent.com/assets/2371472/12920430/319338d4-cf0e-11e5-8c32-cb0ac65d0dc9.png)

You divide each alternating column or row by two, resulting in increasingly smaller windows. 

Motivations include:
- Don't squeeze the existing higher priority windows when adding new windows to the screen.
- Try to keep windows as close to square as possible. Reduce the number of ultra-thin windows on screen.
- Increase the total number of possible usable windows on screen

This is what it would like like if I Option+Shift+H a bit. 
![image](https://cloud.githubusercontent.com/assets/2371472/12921305/30e78800-cf12-11e5-90e8-fe3704cb4425.png)

Note how every window becomes a little thinner, but more windows can fit on screen. Option+Shift+L would make windows more square at the price of fewer usable windows, or something.

![image](https://cloud.githubusercontent.com/assets/2371472/12921537/59f2ac9c-cf13-11e5-844c-0b03003a8803.png)

Thanks again for the awesome app!

[Trello Card](https://trello.com/c/wFkIII7i/197-amethyst-new-layout-request)

**Comment by ianyh** [comment] 2016-02-10 16:13
I think this is a special case of binary space partitioning, but it's still an interesting one. I think I may hold off on this for a short while. I'm considering ways to make layouts not compiled into the application (as JavaScript scripts, for example).

**Comment by gprimosch** [comment] 2016-02-10 19:05
> I think this is a special case of binary space partitioning
Good to know the the right term, thanks.

**Comment by gprimosch** [comment] 2016-02-10 19:14
Apparently it has been done: https://github.com/baskerville/bspwm

**Comment by ianyh** [comment] 2016-02-10 19:40
Yeah. That's not going to work for native OS X windows, though. The algorithm is probably what I would end up using, though.

**Comment by timvisher** [comment] 2016-02-11 18:41
I believe Slate makes this possible as well. Might be worth a look.
https://github.com/jigish/slate

**Comment by chrishoage** [comment] 2016-02-15 23:25
KWM can achieve this layout and is for OS X https://github.com/koekeishiya/kwm/

**Comment by ianyh** [comment] 2016-04-08 00:29
I think this is duplicate of #255

**Closed by ianyh** 2016-04-08 00:29 UTC
Labels: enhancement
