### ISSUE TITLE
Need to switch spaces to trigger layout.

### ISSUE THREAD

**Issue by wting** [ianyh/Amethyst#122] opened 2014-02-20 19:03 UTC
I'm running 212a91dd. When opening a new window (e.g. Command-N within Chrome or iTerm via keyboard shortcut) it is floating and not applied to the layout.

I have to switch to a different space and switch back in order to apply the layout. When I change the layout, all the pre-existing windows are formatted correctly but not the new one. Why is that?

[Trello Card](https://trello.com/c/LH7xmvxt/43-amethyst-need-to-switch-spaces-to-trigger-layout)

**Comment by ianyh** [comment] 2016-05-22 23:55
This should be mitigated by #371, and I think might be a duplicate of #49.

**Closed by ianyh** 2016-05-22 23:55 UTC
Labels: bug
