### ISSUE TITLE
Comparison with kwm

### ISSUE THREAD

**Issue by avindra** [ianyh/Amethyst#538] opened 2017-01-17 19:47 UTC
Hi,

It seems that Kwm shares common goals with `Amethyst`:

https://github.com/koekeishiya/kwm/issues/563

Perhaps it would be useful to document some feature comparisons? It's hard to find documentation, screencasts, screenshots, etc about either, so I thought I'd open up an issue to get it going.

[Trello Card](https://trello.com/c/ulgMEoem/254-amethyst-comparison-with-kwm)

**Comment by ianyh** [comment] 2017-01-30 14:31
Good idea.

**Comment by knightjp** [comment] 2017-05-09 07:29
According to a couple of users, KWM is faster in responding to new windows or maybe faster in general. My personal experience with Amethyst as of a new installation last night was similar. The only thing that I like about Amethyst that it worked well out of the box for me and I didn't have to mess with any config files. 
KWM works well and much in the same manner, but I didn't like the spaces in between windows and the padding around the edges of the screen. 

The one thing the Amethyst has going for it is that it is capable of being installed like a normal app; which does not require Homebrew. That is a good. 
Another good point in Amethyst's favor is that the author of KWM is has stopped working on it and focused on another window managing project. This essentially means that there won't be many updates coming in for KWM soon.

**Comment by ianyh** [comment] 2017-11-12 19:23
Duplicate of #267

**Closed by ianyh** 2017-11-12 19:23 UTC
Labels: enhancement
