### ISSUE TITLE
Throw window to space X not working

### ISSUE THREAD

**Issue by mammuth** [ianyh/Amethyst#686] opened 2018-02-18 11:43 UTC
## System

 - **Amethyst version**: 0.12.0b
 - **macOS version**: 10.13.3

## What's the problem?
_Throw window to space X_ keyboard shortcut is not working. It seems to be triggered when hitting the shortcut, because the mouse shortly jumps to another place within the focused window, but then just returns to previous location. The window does not get moved to the wished space. 

Switching layouts [Tall, wide, fullscreen] doesn't change anything.

## How can it be reproduced?
Hit the corresponding shortcut (alt+shift+ctrl+[1,2,3,4]

## What applications are involved?
Tried it with Chrome, Preview, Finder

**Comment by ianyh** [comment] 2018-02-18 17:25
Have you followed these steps? https://github.com/ianyh/Amethyst#setting-up-spaces-support

**Comment by mammuth** [comment] 2018-02-18 17:40
No.🙈 Sorry for not following the docs in depth

**Comment by ianyh** [comment] 2018-02-18 17:54
That's alright. It's kind of a weird behavior.

**Comment by uloco** [comment] 2018-08-10 08:08
I followed these steps but still can't get it to work on High Sierra. Am I missing something out?

**Comment by nidzola** [comment] 2019-03-10 00:04
Same here, I can't get it working... When I trigger the shortcut, I'm just getting that jumping mouse behavior. I've added spaces inside the mission control etc.

Amethyst version: 0.12.3
macOS version: 10.14.3 Mojave

It would be really great to have this killer feature working. 😄

**Comment by ianyh** [comment] 2019-03-10 00:22
@uloco @nidzola does it consistently happen with all apps or is it only some?

**Comment by nidzola** [comment] 2019-03-10 01:21
@ianyh yeah, no matter which app I try to move/throw to another window, the behavior is the same. I recorded a simple video to show what's the problem: https://screencast-o-matic.com/watch/cqe6VF0v24

**Comment by choppsv1** [comment] 2019-03-10 01:28
I think I hit this problem. It ended up being that I had remapped (or unmapped) the Apple standard keys for switching spaces in System Preferences Keyboard. This might be a common thing for people who change the defaults to try better match their linux tiling WM.

Thanks,
Chris.

**Comment by ianyh** [comment] 2019-03-10 01:32
That is a definite possibility. The spot that mouse is moving to in that video is incorrect, though. Maybe we’re getting the frame wrong?

**Comment by ianyh** [comment] 2019-03-10 01:38
Regardless, probably should reopen this.

**Comment by nidzola** [comment] 2019-03-10 01:42
I tried with both defaulted mapped shortcuts for switching, and with my custom ones, the behavior is the same 😞 ...
Is there a way how to debug what's happening in the background? To extract some logs or anything related to the issue?

**Comment by choppsv1** [comment] 2019-03-10 16:09
Ah, so the fact that you had custom mapped ones mimics my setup when I hit the problem. I wonder if when you reset to the default did you reboot just to make sure everything started fresh?

**Comment by nidzola** [comment] 2019-03-10 18:53
Yeah, did the restart and tried everything that I could, but the issue is still there.

**Comment by x-ji** [comment] 2019-03-12 19:01
I also seem to have encountered this issue. I'm sure it was working a while ago when I last used Amethyst, but now only the focus is moved to that space, not the window/application itself.

**Comment by x-ji** [comment] 2019-03-12 19:09
The behavior is similar to that shown in the screencast by @nidzola The mouse briefly goes appears at the top left of the current window, but the window itself is not moved.

**Comment by badfilms** [comment] 2019-03-26 20:56
While I have no problems throwing to specific spaces, or throwing to left/right space on my primary display, I am having the same issue when trying to throw to space left or space right on my secondary display.

Posting here because the issues seem similar enough, but I can open a new issue if needed.

**Comment by ianyh** [comment] 2019-03-26 21:08
Adding here is fine. I’m going to start using some private APIs for spaces. That would rework the mechanism fairly significantly, but I think would solve a lot of the problems people run in to.

**Comment by ianyh** [comment] 2019-04-13 16:13
#817 should fix this.

**Closed by ianyh** 2019-04-13 16:13 UTC
Labels: bug

**Comment by svermeulen** [comment] 2019-04-14 04:00
Can confirm the new beta fixes the issue, at least for me

**Comment by kkweon** [comment] 2020-09-02 20:20
I'm not able to find a doc anymore (https://github.com/ianyh/Amethyst#setting-up-spaces-support)

Is it because it's supposed to work without any settings now? It's not working for me hence I am browsing if I'm missing something before filing a bug.

**Comment by mhill-shippit** [comment] 2022-02-02 10:34
This issue appears to be biting me now. Fresh install of the entire system, using Monterey on an M1. I can't find any collision with shortcuts - is there anything else I can look into?

**Comment by shahriarfahim870** [comment] 2022-02-12 07:00
Have been struggling with this ever since I stopped using Yabai (due to that being incredibly buggy on M1) and switched to Amethyst. I use Karabiner to remap keys (caps_lock to shift+control+option), and the remapped caps_lock key works fine for other commands (such as moving focus, swapping focused window, etc). I even tried changing the shortcuts to avoid using the remapped caps_lock key (using option+shift as mod key), but that didn't solve anything. Tried uninstalling and Karabiner as well, and that didn't solve anything either.

**Comment by jpbernius** [comment] 2022-02-12 21:55
I also cannot get the spaces to work. Based on the README History, the [deleted documentation](https://github.com/ianyh/Amethyst/commit/a3b6a8e46e035220cd09771b92a9b7a643bdd0d5) for spaces was setting up `Ctrl + n` shortcuts to navigate to a certain space. However,  it appears to me that this should no longer be needed due to some use of a private API?

Nevertheless, I did enable the shortcuts and so far did not see any effect. (Even though the shortcuts are nice to have anyway. 😉)

**Comment by borsboom** [comment] 2022-02-17 01:42
EDIT: looks like #1192 has been opened for this new instance of the problem, which seems to be a Mojave 12.2 compatibility issue.

This also seems to be biting me.  It was working fine since I started using Amethyst a few months ago, and then a week or so ago it stopped working.  I didn't change any settings as far as I know.  I did upgrade from Mojave 12.0 to 12.2 around this time, but I'm not certain whether the timing perfectly coincided.

**Comment by alessandropolverino** [comment] 2022-02-21 17:27
same as @borsboom, after upgrading to 12.2 I cannot throw windows to spaces anymore

**Comment by tonykaram1993** [comment] 2022-02-22 18:42
Same here. I just got a new MacBook M1 Pro on 12.2.1 and moving apps to spaces doesn't work.

On my old MacBook (intel), < 12.2.1 moving apps to spaces works fine. 

I still get the mouse cursor jumping to the center of the app, but the app doesn't move.

**Comment by marek-liska** [comment] 2022-05-23 19:19
same here, M1 air, Monterey 12.4 :(
