### ISSUE TITLE
Focus follows mouse not working with google chrome 72

### ISSUE THREAD

**Issue by s26haide** [ianyh/Amethyst#797] opened 2019-02-26 20:49 UTC
## System
 - **Amethyst version**: 0.12.2
 - **macOS version**: Mojave 10.14.2
- **Chrome version**: 72.0.3626.109

## What's the problem?
Amethyst focus follows mouse is not focusing the google chrome window (it's focusing on all other windows)

## How can it be reproduced?
With multiple displays (not sure if this is relevant), try switching focus between chrome and other windows with focus follows mouse

## What applications are involved?
XCode, ios simulator, google chrome

I have BetterTouchTool installed (it allows window snapping, maybe this is conflicting with amethyst?) Not really sure, I just installed both today.

## Has anything fixed it, even temporarily?
Nope, window focus is changing between XCode and ios simulator (on different monitors) properly, but google chrome (on same monitor as simulator) has never focused before with ffm

## dotfile (if you have one)
N/A

## Screenshots
N/A

**Comment by ianyh** [comment] 2019-02-27 04:53
Duplicate of #754

**Closed by ianyh** 2019-02-27 04:53 UTC

**Comment by s26haide** [comment] 2019-02-27 05:17
I did see that one and it seems fixed and this is still happening for me. Any advice?

**Comment by ianyh** [comment] 2019-02-27 05:23
The fix hasn’t been released yet. Going to try to do a release this week.

**Comment by s26haide** [comment] 2019-02-27 05:24
Ahhh okay I see. Thank you!
