### ISSUE TITLE
Can't disable option to "Start Amethyst on Login"

### ISSUE THREAD

**Issue by ianfixes** [ianyh/Amethyst#773] opened 2018-11-30 13:25 UTC
## System

 - **Amethyst version**: `0.12.1 (61)`
 - **macOS version**: `10.13.6 (17G65)`

## What's the problem?
![nov-30-2018 08-22-37 cant disable amethyst](https://user-images.githubusercontent.com/583459/49291901-b209b180-f479-11e8-8d42-61a3f7f2120c.gif)

**Comment by ianyh** [comment] 2018-12-02 16:08
Duplicate of #673

**Closed by ianyh** 2018-12-02 16:08 UTC
