### ISSUE TITLE
Focus follows mouse option re-enables occasionally

### ISSUE THREAD

**Issue by slaughtr** [ianyh/Amethyst#1052] opened 2020-09-09 22:11 UTC
**Describe the bug**
On rare occasions, the "Focus follows mouse" setting in the preferences becomes re-enabled on my machine. It generally seems to happen when restarting Amethyst (either via hotkey or quitting and re-opening the app), though I _think_ it has happened randomly when switching layouts.

I restart Amethyst via hotkeys fairly often in order to fix BSP layout issues, probably 5-10 times a day. The "Focus follows mouse" option is re-ticked once every couple/few days. Which is to say it doesn't happen incredibly often nor consistently.

**Applications:**
I have any of a couple dozen applications open at any given time, as far as I can tell this is related only to Amethyst.

**To Reproduce**
I am unable to reliably reproduce the bug. I believe restarting Amethyst and switching to BSP on a loop for a while is the best bet for reproduction.

**Expected behavior**
The option should not re-tick whenever it feels like it :)

**Screenshots**

**Versions:**
 - macOS: 10.15.6
 - Amethyst: 0.15.3
 
**Debug Info**
```
~ ❯  /Applications/Amethyst.app/Contents/MacOS/Amethyst --debug-info                                                                                                                                                                            10:51:48 AM
Version: 0.15.3 (88)

OS version: Version 10.15.6 (Build 19G73)

Has permissions: false

Screens:
	(0.0, 0.0, 1792.0, 1120.0) [(0.0, 0.0, 1792.0, 1120.0)]
	(1792.0, -691.0, 1200.0, 1920.0) [(1792.0, -109.0, 1200.0, 1920.0)]
	(-1200.0, -708.0, 1200.0, 1920.0) [(-1200.0, -92.0, 1200.0, 1920.0)]

Manageable applications:
	ViewBridgeAuxiliary (com.apple.ViewBridgeAuxiliary)
	Chromium (org.chromium.Chromium)
	Mail (com.apple.mail)
	iTerm2 (com.googlecode.iterm2)
	HEY (com.hey.app.desktop)
	Microsoft Teams (com.microsoft.teams)
	Control Strip (com.apple.controlstrip)
	Signal (org.whispersystems.signal-desktop)
	ViewBridgeAuxiliary (com.apple.ViewBridgeAuxiliary)
	talagent (com.apple.talagent)
	QuickLookUIService (Finder) (com.apple.quicklook.QuickLookUIService)
	Finder (com.apple.finder)
	AppSSOAgent (com.apple.AppSSOAgent)
	EmojiFunctionRowIM (com.apple.inputmethod.EmojiFunctionRowItem)
	OpenInTerminalHelper (wang.jianing.app.OpenInTerminalHelper)
	Vanilla (net.matthewpalmer.Vanilla)
	Activity Monitor (com.apple.ActivityMonitor)
	Code (com.microsoft.VSCode)
	coreautha (com.apple.LocalAuthentication.UIAgent)
	Google Play Music Desktop Player (google-play-music-desktop-player)
	BTTRelaunch (com.hegenberg.BTTRelaunch)
	BetterTouchToolAppleScriptRunner (com.hegenberg.BetterTouchToolAppleScriptRunner)
	BetterTouchToolAppleScriptRunner (com.hegenberg.BetterTouchToolAppleScriptRunner2)

Configuration:
window-margin-size: 0
window-resize-step: 5
focus-follows-mouse: 0
mouse-follows-focus: 0
floating-is-blacklist: 1
float-small-windows: 1
enables-layout-hud-on-space-change: 1
screen-padding-top: 0
new-windows-to-main: 0
ignore-menu-bar: 0
follow-space-thrown-windows: 1
mod2: (
    option,
    shift,
    control
)
enables-layout-hud: 1
screen-padding-bottom: 0
screen-padding-right: 0
window-minimum-width: 0
debug-layout-info: 1
floating: (
        {
        id = "com.googlecode.iterm2";
        "window-titles" =         (
            "Hotkey Window"
        );
    },
        {
        id = "com.parallels.desktop.console";
        "window-titles" =         (
        );
    }
)
restore-layouts-on-launch: 0
use-canary-build: 0
window-margins: 0
layouts: (
    fullscreen,
    floating,
    row,
    bsp
)
screen-padding-left: 0
window-minimum-height: 0
mod1: (
    option,
    shift
)
```

**Additional context**
I use 2 external monitors + my MacBook, if that's important.

**Comment by ianyh** [comment] 2020-10-09 02:42
Duplicate of #995, I think.

**Closed by ianyh** 2020-10-09 02:42 UTC

**Comment by slaughtr** [comment] 2020-10-09 16:48
I am not entirely sure if it is a duplicate, though it very well may be related.

I stopped using BSP entirely (due to having to reset amethyst so often to fix issues) and I haven't had focus follow mouse re-enable since. This leads me to believe that restarting amethyst (via keyboard shortcuts) might be the root cause of my issue.
