### ISSUE TITLE
Current layout name is shown even for fullscreen apps

### ISSUE THREAD

**Issue by Jabher** [ianyh/Amethyst#849] opened 2019-08-13 08:47 UTC
## System

 - **Amethyst version**:
0.14.0
 - **macOS version**:
10.14.5
## What's the problem?
When swiping between workspaces, current layout name is shown even when app is working in fullscreen mode.
## How can it be reproduced?
swipe between fullscreen apps
## What applications are involved?
any, currently - Chrome, IntelliJ IDEA
## Has anything fixed it, even temporarily?
no

**Comment by ianyh** [comment] 2019-08-13 10:13
Duplicate of #559

**Closed** 2019-08-13 10:14 UTC
Labels: bug, duplicate
