### ISSUE TITLE
Amethyst occasionally destroys floating layouts

### ISSUE THREAD

**Issue by colons** [ianyh/Amethyst#287] opened 2015-02-05 15:05 UTC
When quickly switching between floating and non-floating desktops with the three-finger trackpad gesture, sometimes Amethyst will rearrange windows in a way that looks like it's trying to arrange two desktops worth of windows at once. I've uploaded [a video of this happening](http://youtu.be/gITs5JQE04M) (first actual instance at ~0'43"). It's maybe like 2-5% of desktop switches that cause it to happen, but my workflow involves a lot of quickly switching between desktops.

**Comment by ianyh** [comment] 2015-02-18 15:06
I think this is a duplicate of #207

**Closed by ianyh** 2015-02-18 15:06 UTC
Labels: bug
