### ISSUE TITLE
Assigning a layout to a space

### ISSUE THREAD

**Issue by joelbrewster** [ianyh/Amethyst#432] opened 2016-04-12 02:21 UTC
I'd like to propose the ability to assign layouts to each space via the amethyst config (~/.amethyst).
Something like this:

"Space-1": tall,
"Space-2": fullscreen,
"Space-3": fullscreen,
"Space-4": floating

Also, add the window margins to the config file.

**Comment by ianyh** [comment] 2016-04-14 13:43
I think this is a duplicate of #302.

Window margins are available for config files. See the `window-margins` and `window-margin-size` keys in `default.amethyst`.

**Closed by ianyh** 2016-04-14 13:43 UTC
