### ISSUE TITLE
Resizing main pane to full pushes VLC window offscreen permanently

### ISSUE THREAD

**Issue by joshproehl** [ianyh/Amethyst#203] opened 2014-08-28 20:28 UTC
So far I have only observed this with VLC. Unsure if this is a bug in VLC itself, or something Amethyst is doing to it.

With any app and VLC window split in "Tall" mode, and VLC in the secondary (left) pane, showing it's playlist and sidebar:
Resize the main pane to be increasingly larger. It continues to expand until it is full screen, which hides VLC offscreen, where it can never be brought back until it is relaunched. (Resizing back down does nothing, VLC menus cannot bring it back, clicking icon in dock brings you to correct space but cannot recover VLC window.)

This also occurs if the left pane (the one being squashed) contains both VLC and another app. The other app comes back fine, but VLC has still vanished and must be relaunched. 

[Trello Card](https://trello.com/c/w35PNMil/69-amethyst-resizing-main-pane-to-full-pushes-vlc-window-offscreen-permanently)

**Comment by ianyh** [comment] 2017-07-18 16:02
Closing as a duplicate of #626

**Closed** 2017-07-18 16:01 UTC
Labels: bug
