### ISSUE TITLE
Does not detect and resize windows without a title bar/borderless windows

### ISSUE THREAD

**Issue by neonfrontier** [ianyh/Amethyst#300] opened 2015-04-15 23:49 UTC
Hello, 
I'm not too sure if this is an issue here or with iterm2. 
I tested the iterm nightly build for the option to remove the title bar, but discovered that Amethyst didn't resize it without the title bar.
Nightly builds: https://iterm2.com/downloads/nightly/#/section/home
The option I was testing: http://i.imgur.com/TZCJU9G.jpg
If it's an iterm2 issue i'll be happy to take it to them instead!
Thanks!

[Trello Card](https://trello.com/c/NhefRuRi/129-amethyst-does-not-detect-and-resize-windows-without-a-title-bar-borderless-windows)

**Comment by leonardt** [comment] 2015-04-16 18:55
dupe of https://github.com/ianyh/Amethyst/issues/200

It's an issue with how the window reports (as a non standard window, which Amethyst ignores so it doesn't try to tile popups).  Two possible workarounds, add a list of non standard windows to force tiling on, or find out what type of window iTerm is reporting as and tile those types.

**Comment by neonfrontier** [comment] 2015-04-17 00:23
thank you for the info!

**Comment by ianyh** [comment] 2015-04-17 00:25
Thanks @leonardt

**Closed by ianyh** 2015-04-17 00:25 UTC
