### ISSUE TITLE
Amethyst does not recognize Eclipse start

### ISSUE THREAD

**Issue by dcharkes** [ianyh/Amethyst#379] opened 2016-01-06 10:34 UTC
In order to tile Eclipse I have to use `mod+t` or relauch Amethyst.

This holds for both Eclipse Luna and Eclipse Mars.

Probably same issue as: https://github.com/ianyh/Amethyst/issues/286

[Trello Card](https://trello.com/c/rIUVVYjY/187-amethyst-amethyst-does-not-recognize-eclipse-start)

**Comment by ianyh** [comment] 2016-01-13 22:28
Yeah. It may also be a symptom of #49. I haven't tested any Java-based applications, though, so it might be a platform specific thing (though I find that somewhat unlikely), so I'll leave this open for now. There's some discussion in that issue about potential ways to solve this if you're curious.

**Comment by dzeruel** [comment] 2017-05-23 09:34
Hello! I have similar symptoms. A java based application window don't get tiled.

**Comment by ianyh** [comment] 2017-07-25 00:45
Duplicate of #49

**Closed by ianyh** 2017-07-25 00:45 UTC
Labels: bug
