### ISSUE TITLE
Issues with Multiple Windows in Tall Right Layout

### ISSUE THREAD

**Issue by CKolkey** [ianyh/Amethyst#951] opened 2020-02-18 19:23 UTC
**Describe the bug**
With more than one window open in Tall Right, the non-primary window(s) are not being placed correctly. With only two windows, the left window jumps to the correct place on focus, but reverts when focus is lost. With three windows, it appears that one of the left windows will jump on focus, but the rest will not.

The issue is more pronounced in a second monitor.

**Applications:**
It does not appear to matter. Any window is effected. 

**To Reproduce**
Upgrade to 0.14.4
In primary or secondary monitor, open two windows while in Tall Right layout.
Focus and Unfocus the left window. Watch it jump around. 

**Expected behavior**
Not jumping around. 

**Video**
- (Primary Monitor)  https://youtu.be/DnQnZTjQ4oo 
- (Secondary Monitor) https://youtu.be/h6LUasg3q_s 

**Versions:**
 - macOS: 10.14.6
 - Amethyst: 0.14.4 (81)

**Additional context**
Began *immediately* after upgrading to 0.14.4, from 0.14.3, with no changes to configuration

**Comment by ianyh** [comment] 2020-02-18 19:53
Is this a duplicate of #933?

**Comment by CKolkey** [comment] 2020-02-19 09:35
@ianyh Yea, that seems to be the case

**Closed** 2020-02-19 13:09 UTC
Labels: bug, duplicate
