### ISSUE TITLE
Using amethyst from the terminal + config file

### ISSUE THREAD

**Issue by corpooo** [ianyh/Amethyst#1112] opened 2021-04-22 06:35 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'd like to be able to use amethyst from the terminal. E.g: Switching the layout, focusing app/screen, moving app/screen
I'd like to have a config file foy my keybingings, layouts, white/black-lists.

**Comment by ianyh** [comment] 2021-07-03 01:21
Duplicate of #717, I think.

**Closed as completed by ianyh** 2021-07-03 01:21 UTC
Labels: duplicate, enhancement, help wanted

**Comment by Uzaaft** [comment] 2022-07-03 17:57
@andreicorpo  Config file is now available in [0.16.0 beta](https://github.com/ianyh/Amethyst/releases/tag/v0.16.0b). For docs see: https://github.com/ianyh/Amethyst/blob/development/docs/configuration-files.md
