### ISSUE TITLE
Option to launch new windows as master not slave

### ISSUE THREAD

**Issue by sublimator** [ianyh/Amethyst#284] opened 2015-01-22 12:09 UTC
I come from linux/awesome, where the default behaviour is to launch new windows as master, which to me at least seems more sensible. No doubt others would disagree, hence I humbly, pretty please beg for an option :)

**Comment by ianyh** [comment] 2015-01-22 12:51
Duplicate of #64

**Closed by ianyh** 2015-01-22 12:51 UTC
