### ISSUE TITLE
Changing a single window to fullscreen

### ISSUE THREAD

**Issue by knightjp** [ianyh/Amethyst#733] opened 2018-07-20 21:20 UTC
## System

 - **Amethyst version**: 0.12.0 (57)
 - **macOS version**: 10.13.6

## What's the problem?
This might already be possible, but how do I get just the focused window to fullscreen without changing the whole layout to the "fullscreen" mode. 
Thus I can keep just the rest of the windows in "floating" or "bsp" mode. 

Prior to using Amethyst, I was using the Moom app, and it gave me option like this for just a single window.. 
![moom](https://user-images.githubusercontent.com/14360736/43025774-17394f38-8c84-11e8-83b8-a40a652b5afd.png)

It would be nice to have a single shortcut or something.

**Comment by ianyh** [comment] 2018-08-10 22:34
I think this is a duplicate of #656

**Closed by ianyh** 2018-08-10 22:34 UTC
