### ISSUE TITLE
Firefox windows do not split

### ISSUE THREAD

**Issue by knightjp** [ianyh/Amethyst#604] opened 2017-06-30 11:16 UTC
When using Amethyst, all the windows on my computer responds and split when a new application is started or a new windows is opened. All except Firefox. If Firefox is taking up the whole screen space, it does not split when I load up another app like Safari or Chrome... 
I have to minimize the Firefox window to see the other windows behind it. 

Any ideas as to why this is happening?

**Comment by ianyh** [comment] 2017-07-02 02:07
Duplicate of #49

**Closed by ianyh** 2017-07-02 02:07 UTC
