### ISSUE TITLE
Play nice with Spectacles or ShiftIt

### ISSUE THREAD

**Issue by luisdavim** [ianyh/Amethyst#541] opened 2017-01-25 10:31 UTC
I use Spectacles to move windows it would be nice if either Amathyst had the same features built in or if at least would play nice with it.
For example, If I'm using the tall layout and I have two windows tiled vertically and I move the one from to let to the right I expect the window on the right to automatically move to the left where the other window previously was.

This is the default behaviour in other tiling window managers like i3.
I hope my explanation was clear.

Luis

**Comment by ianyh** [comment] 2017-01-30 14:29
I think this is a duplicate of #180 . The problem is that we don't readjust layouts based on externally applied changes.

**Closed by ianyh** 2017-01-30 14:29 UTC
Labels: duplicate, enhancement
