### ISSUE TITLE
Reverse Layout Option

### ISSUE THREAD

**Issue by stylerw** [ianyh/Amethyst#288] opened 2015-02-08 19:10 UTC
So, my setup is such that I'd really like a "Tall-Reversed" setup, where the main pane is on the left.  I'm not sure if there's a way to modify that in the latest version or not, but it'd be spectacular to be able to customize in that way.

Thanks, great software :)

**Comment by ianyh** [comment] 2015-02-18 15:04
Duplicate of #129

**Closed by ianyh** 2015-02-18 15:04 UTC
