### ISSUE TITLE
Firefox stuttering or not adhering to Amethyst window layout

### ISSUE THREAD

**Issue by KingOfSpades** [ianyh/Amethyst#1119] opened 2021-05-18 18:02 UTC
**Describe the bug**
Does anyone else experience this issue when using Amethyst and Firefox? Really curious if it's just a local issue.

When using Amethyst on macOS (11.3.1 (20E241)) Firefox behaves strangely. It does not always seem to conform to the selected layout.

**Applications:**
- Amethyst
- Firefox

**To Reproduce**
Start a Firefox window with Amethyst running. Create 1 or more additional windows and change layout. After the window rearangement the modifers for `Force windows to be reevalulated` have to be pressed several times (<kbd>mod1 + z</kbd>)

**Expected behavior**
That Firefox picks up on the tilling like other applications

**Screenshots (video)**
https://user-images.githubusercontent.com/2156115/118701133-acec7880-b813-11eb-8a76-3d4d2e96ecaf.mov

**Versions:**
 - macOS: 11.3.1 (20E241)
 - Amethyst: 0.15.4 (91)
 - Firefox: 88.0.1 (64-bit)
 
**Debug Info**
```
Version: 0.15.4 (91)

OS version: Version 11.3.1 (Build 20E241)

Has permissions: false

Screens:
	(0.0, 0.0, 1920.0, 1080.0) [(0.0, 0.0, 1920.0, 1080.0)]
	(1920.0, 0.0, 1920.0, 1080.0) [(1920.0, 0.0, 1920.0, 1080.0)]

Manageable applications:
	Safari (com.apple.Safari)
	Finder (com.apple.finder)
	Firefox (org.mozilla.firefox)

Configuration:
new-windows-to-main: 0
screen-padding-left: 0
mod2: (
    option,
    shift,
    control
)
floating: (
        {
        id = "info.v002.Camera-Live";
        "window-titles" =         (
        );
    },
        {
        id = "com.orban.OrbanLoudnessMeter";
        "window-titles" =         (
        );
    }
)
window-margin-size: 5
restore-layouts-on-launch: 1
mouse-follows-focus: 0
window-minimum-height: 0
screen-padding-top: 0
layouts: (
    tall,
    wide,
    fullscreen,
    column
)
follow-space-thrown-windows: 1
enables-layout-hud: 1
window-minimum-width: 0
use-canary-build: 0
mod1: (
    option,
    shift
)
float-small-windows: 1
debug-layout-info: 0
mouse-swaps-windows: 1
screen-padding-right: 0
screen-padding-bottom: 0
enables-layout-hud-on-space-change: 0
mouse-resizes-windows: 0
focus-follows-mouse: 0
window-margins: 1
floating-is-blacklist: 1
ignore-menu-bar: 0
window-resize-step: 5
```

**Comment by Amparose** [comment] 2021-11-02 17:24
I have noticed this with Firefox and Amethyst but also with other window managers like Magnet. So I think it is more a FF issue than Amethyst.

**Comment by auscompgeek** [comment] 2022-07-18 05:26
Duplicate of #1257?

**Comment by ianyh** [comment] 2023-01-31 01:53
Yes. Duplicate.

**Closed as completed by ianyh** 2023-01-31 01:53 UTC
Labels: bug, duplicate
