### ISSUE TITLE
Resize rows instead of columns

### ISSUE THREAD

**Issue by jrock2004** [ianyh/Amethyst#637] opened 2017-08-07 16:48 UTC
## System

 - **Amethyst version**: 0.11.3
 - **macOS version**: Sierra

## How can it be reproduced? Be in the row format

```
 F |  X
    | Z
```

So I want to make X height smaller, while make Z larger
## Screenshots

[Trello Card](https://trello.com/c/ksSzcOme/284-amethyst-resize-rows-instead-of-columns)

**Comment by ifreecarve** [comment] 2017-08-24 04:13
Currently there is no support to change a secondary dimension of the tiled windows.  There is only a "main" and a "secondary" group, with all other ratios being hard-coded.

**Comment by ianyh** [comment] 2017-11-12 18:34
Yeah, this is kind of a fundamental limitation. Most of the layouts are intentionally simple as the structures of more complicated layouts like this introduce a lot of logic and some ambiguity; e.g., does adding a window cause windows that have modified dimensions to maintain there dimension modifications? In that case what happens if their modification was on the axis that the window is being added to? Does it keep a static difference? It's a big can of worms.

I think this is also a duplicate of #82, so going to close it for now.

**Closed by ianyh** 2017-11-12 18:34 UTC
