### ISSUE TITLE
Allow custom keyboard shortcuts for spaces

### ISSUE THREAD

**Issue by mitar** [ianyh/Amethyst#612] opened 2017-07-07 05:28 UTC
## System

 - **Amethyst version**: 0.10.1 (37)
 - **macOS version**: 10.10.5

## What's the problem?

It seems Amethyst spaces shortcuts to be control+number, but I use command+function key. So I do have shortcuts enabled, but they are different. Maybe Amethyst could read what is existing shortcut for a space and use it?

**Comment by ianyh** [comment] 2017-07-07 18:42
Duplicate of #409, but I am forced to point out that Amethyst stopped supporting macOS versions earlier than 10.12 a while back.

**Closed by ianyh** 2017-07-07 18:42 UTC
