### ISSUE TITLE
A few apps not tiling correctly

### ISSUE THREAD

**Issue by brettneese** [ianyh/Amethyst#348] opened 2015-11-13 21:56 UTC
May be related to #347, but I've noticed that after updating to 0.9.6 Webstorm and iTerm seem to refuse tile and just kind of float. I've disabled "Float small windows," to ensure that it wasn't an issue with the way Webstorm was reporting it's window size, or something.

What can I do to help get this fixed?

I'm on 10.11.

[Trello Card](https://trello.com/c/vIKrK6fp/175-amethyst-a-few-apps-not-tiling-correctly)

**Comment by ianyh** [comment] 2015-11-13 21:57
Does `mod1+t` not affect them at all?

**Comment by brettneese** [comment] 2015-11-13 22:11
Not as far as I can tell :(

Also just noticed that 0.9.7 was pushed out, but the same issue is happening. 

Is there a way to force a re-tile, or is that what `mod1+t` does?

(I don't think it was happening in 0.9.5, but I was having those issues with the way Amethyst was dealing with full-screen windows.)

**Comment by horshacktest** [comment] 2016-04-30 16:59
If you have spaces enabled, I've found that swiping to the adjacent space and back again will trigger a re-layout most of the time with most apps. I've gotten some unique crazyness with intellij tho, so webstorm will probably be the same.

**Comment by net** [comment] 2017-01-11 06:03
For iTerm go to Profiles > Window and make sure Space is set to Current Space.

**Comment by ianyh** [comment] 2017-07-25 00:50
This was likely a duplicate of #49

**Closed by ianyh** 2017-07-25 00:50 UTC
Labels: bug
