### ISSUE TITLE
Request: Focus-follows-mouse delay

### ISSUE THREAD

**Issue by anoother** [ianyh/Amethyst#676] opened 2018-01-24 10:00 UTC
Would it be possible to add a configurable delay before focussing a window in focus-follows-mouse mode? 

This would help prevent windows flashing in and out of focus while moving the mouse to actual destination windows.

**Comment by ianyh** [comment] 2018-01-31 12:24
Duplicate of #638

**Closed by ianyh** 2018-01-31 12:24 UTC

**Comment by anoother** [comment] 2018-02-01 14:32
Ah, didn't realize autoraise and FFM aren't separable :(
