### ISSUE TITLE
When using 3Column Middle layout direction for moving focus is reversed

### ISSUE THREAD

**Issue by blue-3** [ianyh/Amethyst#1462] opened 2023-03-15 23:12 UTC
**Describe the bug**
When using 3Column Middle layout direction for moving focus is reversed. meaning that when i use the kb shortcut to move focus counter clockwise, it does so clockwise (and vise versa)

**To Reproduce**
1. set layout to 3ColumnMiddle
2. open 3 - 5 windows on the screen
3. move focus counter clockwise (it will move clockwise)

**Expected behavior**
- moves focus counter clockwise

**Versions:**
 - macOS: 13.2.1
 - Amethyst: 0.19.0
 
**Debug Info**
```
Version: 0.19.0 (103)

OS version: Version 13.2.1 (Build 22D68)

Screens:
	(0.0, 0.0, 3440.0, 1440.0) [(0.0, 0.0, 3440.0, 1440.0)]
	(-1440.0, 0.0, 1440.0, 900.0) [(-1440.0, 540.0, 1440.0, 900.0)]
	(539.0, -954.0, 1373.0, 954.0) [(539.0, 1440.0, 1373.0, 954.0)]

Configuration:
window-max-count: 0
focus-follows-mouse: 0
new-windows-to-main: 0
mouse-resizes-windows: 1
enables-layout-hud: 1
screen-padding-bottom: 0
mouse-swaps-windows: 0
window-margin-size: 4
screen-padding-left: 0
smart-window-margins: 0
restore-layouts-on-launch: 0
float-small-windows: 1
mod2: (
    option,
    shift,
    control
)
use-canary-build: 1
enables-layout-hud-on-space-change: 0
debug-layout-info: 0
floating: (
        {
        id = "org.openvpn.client.app";
        "window-titles" =         (
        );
    },
        {
        id = "com.apple.archiveutility";
        "window-titles" =         (
        );
    },
        {
        id = "com.authy.authy-mac";
        "window-titles" =         (
        );
    },
        {
        id = "com.apple.Home";
        "window-titles" =         (
        );
    },
        {
        id = "com.apple.Stickies";
        "window-titles" =         (
        );
    }
)
mod1: (
    option,
    shift
)
ignore-menu-bar: 0
mouse-follows-focus: 1
screen-padding-top: 0
layouts: (
    tall,
    wide,
    fullscreen,
    "two-pane",
    floating,
    "middle-wide"
)
window-minimum-width: 0
window-resize-step: 5
follow-space-thrown-windows: 1
window-minimum-height: 0
screen-padding-right: 0
window-margins: 1
floating-is-blacklist: 1
```

**Comment by ianyh** [comment] 2023-03-18 16:26
Duplicate of #1244.

**Closed as not planned** 2023-03-18 16:26 UTC
Labels: duplicate, layout
