### ISSUE TITLE
If one app is running, it remains in one pane in tall layout.

### ISSUE THREAD

**Issue by bassamsdata** [ianyh/Amethyst#1332] opened 2022-10-27 21:34 UTC
**Is your feature request related to a problem? Please describe.**
Whenever I close all windows except one in a tall layout, the remaining window goes to full screen.
As it stands, the window (the application) doesn't stay (or fill) one half of the screen, which I can expect from tiling manager since I'm still in tall layout.

**Describe the solution you'd like**
In a tall layout (for example), with just one application running in one screen (space), the application stays on half the screen (one pane—half the screen), according to the tall layout, and if I want it full screen, I can activate the full screen layout.

**Describe alternatives you've considered**
Ideally, we would be able to activate a feature like that in a specific layout, either in the settings of the application or in the configuration file.

**Additional context**
If a new application is opened, it goes to the available half pane or to the main pane (it returns to the tall default).
A few popular Linux window tiling managers offer this feature.

Thanks in advance.

**Comment by ianyh** [comment] 2022-10-27 22:38
Duplicate of #83.

**Closed as not planned** 2022-10-27 22:38 UTC
Labels: duplicate, enhancement

**Comment by bassamsdata** [comment] 2022-10-28 01:13
thanks for the reply, I really went deep in the configurations but I really don't know swift. But what I understood that I can change in the javascript file of the tall layout and add it manually but the file mentioned in #83 doesn't work any more (it was 2013). And the problem i couldn't find the tall layout javascript file (I only found the swift).
Is it possible to get the tall layout javascript file please?
