### ISSUE TITLE
[Feature request] Faceless app

### ISSUE THREAD

**Issue by knightjp** [ianyh/Amethyst#608] opened 2017-07-02 05:25 UTC
When I was using [Moom](https://manytricks.com/moom/), I always switched the app to faceless where there wasn't any sign that the app was running. It was just running in the background. 
My menu bar would look quite vanilla after that setting. 
One of the things that I like about KWM as compared to Amethyst is its ability to run in the background with any icon showing on the dock or menu bar. To access the app setting you can  assign a hotkey.

**Comment by mitar** [comment] 2017-07-07 05:25
I would love this as well.

Or to access the app you could just simply run it again and it would show UI.

**Comment by ianyh** [comment] 2017-07-16 22:02
Duplicate of #299

**Closed by ianyh** 2017-07-16 22:02 UTC
Labels: duplicate, enhancement
