### ISSUE TITLE
v0.16: sending app window to another desktop maximizes the window

### ISSUE THREAD

**Issue by HanSooloo** [ianyh/Amethyst#1300] opened 2022-09-06 16:37 UTC
**Describe the bug**
v0.16: sending app window to another desktop maximizes the window.

**Applications:**
Any application, e.g., Firefox, Outlook, Messages, etc.

**To Reproduce**

1. Set "Throw focused window to space X" shortcuts to Ctrl-Opt-Shift-1 and -2.
2. Ensure that there are at least 2 desktops configured.
3. Start Firefox, or any other app  that you want.
4. Use the throw shortcut

**Expected behavior**
App moves to the desired desktop space

**Screenshots**
N/A

**Versions:**
 - macOS: 12.5.1
 - Amethyst: 0.16.0 (94)
 
**Debug Info**
```
$  /Applications/Amethyst.app/Contents/MacOS/Amethyst --debug-info
Version: 0.16.0 (94)

OS version: Version 12.5.1 (Build 21G83)

Screens:
	(0.0, 0.0, 3360.0, 1890.0) [(0.0, 0.0, 3360.0, 1890.0)]
	(3360.0, 131.0, 2048.0, 1280.0) [(3360.0, 479.0, 2048.0, 1280.0)]
	(-3360.0, 373.0, 3360.0, 1890.0) [(-3360.0, -373.0, 3360.0, 1890.0)]

Configuration:
mod1: (
    option,
    shift
)
restore-layouts-on-launch: 0
floating-is-blacklist: 1
window-minimum-width: 0
use-canary-build: 0
screen-padding-right: 0
screen-padding-left: 0
window-minimum-height: 0
follow-space-thrown-windows: 1
window-resize-step: 5
mouse-follows-focus: 0
debug-layout-info: 0
screen-padding-top: 0
enables-layout-hud: 0
floating: (
)
mod2: (
    option,
    shift,
    control
)
enables-layout-hud-on-space-change: 0
ignore-menu-bar: 0
window-margin-size: 0
screen-padding-bottom: 0
focus-follows-mouse: 0
float-small-windows: 0
new-windows-to-main: 0
layouts: (
)
window-margins: 0

```
Note: `--include-apps` will list your manageable applications, but is optional if you don't want to list that.

**Additional context**
Rolling back to 0.15.6 fixes this problem.

**Comment by HanSooloo** [comment] 2022-10-24 15:10
Is there any indication as to what the root cause is?  I forgot this issue existed and did an auto-update and ran into the issue again with Build 94.

**Comment by ianyh** [comment] 2023-01-24 00:15
For the root cause, I believe it was introduced when support for throwing to spaces on different screens was implemented. That requires scaling down the window if moving to a smaller screen, but I think we can just not do the scaling if it's the same screen.

**Comment by noel-yap** [comment] 2023-02-06 15:23
If that's the case, is it possible to scale to the min of the current window size and the screen size?

**Closed as completed** 2023-04-01 13:02 UTC
Labels: bug

**Comment by xerebus** [comment] 2023-08-07 19:01
0.20.0 partially fixes this issue - it still happens sometimes in multi-monitor setups when the "Displays have separate spaces" system setting is off. If the thrown window was originally un-maximized on a secondary monitor, it ends up maximized on the primary monitor.

**Comment by noel-yap** [comment] 2023-08-07 19:09
@xerebus , how do I go about updating to 0.20.0?
