### ISSUE TITLE
Show space number on Amethyst menu bar icon

### ISSUE THREAD

**Issue by macsmister** [ianyh/Amethyst#1090] opened 2021-01-05 15:06 UTC
Don't get me wrong, the Amethyst menu bar icon is beautiful! But it could also be more useful! Imagine if it could track what space number you are in at any given time, and display the space number (optionally a space label too) next to it's logo. I don't want to use spacebar just for this... or bitbar. I feel like this feature should be baked in to give better visual queues.
![Screen Shot 2021-01-05 at 10 00 08](https://user-images.githubusercontent.com/47398571/103662141-96691300-4f3d-11eb-9a6c-d7e812dc4af4.png)

**Comment by ipstone** [comment] 2021-05-29 20:10
I am also looking for a similar feature, currently, I am running the following for this solution, but ideally, it can be included in amethyst, or include in the 'Display Current Layout' function of Amethyst.

The app I am using to show desktop is:  https://github.com/gechr/WhichSpace

**Comment by ianyh** [comment] 2023-03-03 13:52
Duplicate of #1007

**Closed as not planned by ianyh** 2023-03-03 13:52 UTC
