### ISSUE TITLE
Forcing a command line app to float 

### ISSUE THREAD

**Issue by colormotor** [ianyh/Amethyst#1048] opened 2020-08-24 16:22 UTC
Hi, I am developing a prototype OpenGL app that opens a window from the command line and  (as far as I know) does not have a bundle identifier
Is there a way to tell Amethyst to treat the window as "floating" ? Or is there a workaround to get this to work?
 
**Describe the solution you'd like**
I would like to insert the process name in the Floating dialog, but this currently only seems to works with bundles.

**Describe alternatives you've considered**
I tried adding a blank entry to the list, and specifying the window name in question, but this does not seem to work. 
I currently have to resize the window and mark it as floating manually.

**Additional context**
I think this would be generally useful for developers that work on cross-platform graphics applications (e.g. using GLFW) since these are not often bundled as an OSX application.

**Comment by ianyh** [comment] 2020-10-09 02:49
Duplicate of #795

**Closed by ianyh** 2020-10-09 02:49 UTC
