### ISSUE TITLE
Restore window layout after restart

### ISSUE THREAD

**Issue by mutantcornholio** [ianyh/Amethyst#730] opened 2018-06-27 21:50 UTC
If I restart Amethyst (or if Amethyst crashes :D), window layout resets to "fullscreen" on each display.

Maybe it should drop layout config for each desktop on disk and load it on start?

**Comment by ianyh** [comment] 2018-06-28 00:03
Duplicate of #151

**Closed** 2018-06-28 00:03 UTC
Labels: duplicate, enhancement

**Comment by mutantcornholio** [comment] 2018-06-28 01:51
Oh, totally. Sorry.

**Comment by ianyh** [comment] 2018-06-28 02:13
No worries.
