### ISSUE TITLE
Problem with moving windows between spaces

### ISSUE THREAD

**Issue by ikecoglu** [ianyh/Amethyst#1646] opened 2024-05-19 21:58 UTC
**Describe the bug**
I am unable to move windows between spaces using keyboard shortcuts after updating my macOS to Sonoma 14.5.  The window flickers when I attempt to move it but remains on the current space. This issue occurs consistently across all applications I have tested.

**To Reproduce**
1. Update macOS to Sonoma 14.5.
2. Open any application and create multiple desktops.
3. Attempt to move a window to another space using the keyboard shortcut "Ctrl+Option+Shift+Arrow Key (Right or Left)".

**Expected behavior**
The window should seamlessly move to the targeted space when the keyboard shortcut is pressed, as it did prior to the OS update.

**Troubleshooting Steps Attempted**

- Relaunching the application.
- Completely quitting and restarting the application.
- Restarting the computer.

Despite these attempts, the issue persists.

**Versions:**
 - macOS: Sonoma 14.5
 - Amethyst: 0.21.0

**Comment by ianyh** [comment] 2024-05-19 23:40
Duplicate of #1643

**Closed as not planned** 2024-05-19 23:40 UTC
