### ISSUE TITLE
"Move to window to space" feature leaves a copy of the window on the old space

### ISSUE THREAD

**Issue by hetul** [ianyh/Amethyst#1174] opened 2021-12-30 00:52 UTC
**Describe the bug**
When using the hotkey to move a window to a different workspace, the window is also left on the old space (the window will actually appear in both the new space and the old space).

When using the hotkey again, the window will appear in 2 spaces (in practice, it will stick to the space it originally started in, and whatever latest space you assigned it to).

**Applications:**
This happened on all windows that I tried.

**To Reproduce**
* Start Amethyst
* Press the hotkey to assign the window to a different space
* Go back to the original space, and observe that the window is still there. It is also on the new space

**Expected behavior**
The window should not appear on the old space, once it has been assigned to a new space

**Screenshots**
N/A

**Versions:**
 - macOS: Monterey 12.1 (MacBook Pro 14-inch, 2021)
 - Amethyst: 0.15.5
 
**Debug Info**
I can add this later if needed. I ended up uninstalling for now so I don't have debug info.

**Additional context**
I looked into the source code a bit over here: https://github.com/ianyh/Amethyst/blob/development/Amethyst/Model/Window.swift#L315-L316

Amethyst uses private APIs to move windows around.

I suspect, that in the latest version of OSX, the `CGSRemoveWindowsFromSpaces` private API no longer removes the window from a space if it would leave the window with no spaces.

Simply re-ordering the calls to "Add Windows to Spaces" and "Remove Windows from Spaces" may solve the issue.

I actually made my own xcode project to switch spaces around using the same APIs, and found that re-ordering the calls solves the issue there.

I would put up a pull request to fix the code in Amethyst, but I don't currently have the time to figure out how to build/test Amethyst (and make sure it doesn't break on older OSX versions). If I do get a chance later, I'll come back here and set up a PR.

**Comment by haukebruno** [comment] 2022-01-04 06:30
I can confirm this. Upgraded to Monterey yesterday and have the same issue now. My Amethyst is also on `0.15.5`

**Comment by rdamazio** [comment] 2022-01-06 20:23
+1, also seeing this on Monterey 12.1 - especially annoying in combination with #1167 since upon waking from sleep I need to keep moving windows back to their proper space.

**Comment by IshaanG** [comment] 2022-01-13 16:26
Can confirm, having the same issue on Monterey. 
As a temporary workaround, if you have follow thrown window disabled, pressing the hotkey twice removes the window from current workspace. Hope there is a fix soon.

**Comment by dzanotto** [comment] 2022-01-14 11:57
Same problem here, after upgrading to Monterey 12.1
I've testes also the fix mentioned by @hetul and it works, both with "follow thrown window..." enabled and disabled.

**Comment by antoniopantaleo** [comment] 2022-01-20 11:33
> Same problem here, after upgrading to Monterey 12.1
> I've testes also the fix mentioned by @hetul and it works, both with "follow thrown window..." enabled and disabled.

Hasn't this been merged?

**Comment by dzanotto** [comment] 2022-01-20 12:12
> Hasn't this been merged?

I've just created a PR for it -> https://github.com/ianyh/Amethyst/pull/1184

**Closed as completed** 2022-01-21 01:55 UTC
