### ISSUE TITLE
Amethyst and Vivaldi Browser not Playing Nicely

### ISSUE THREAD

**Issue by cesar-programs** [ianyh/Amethyst#1232] opened 2022-05-01 19:31 UTC
**Describe the bug**
Tiling does not operate as intended when Vivaldi browser is used--specifically, there is overlapping that occurs.  

**Applications:**
What applications are involved?
Vivaldi Browser 

**To Reproduce**
Have Amethyst Running 
Open multiple windows to confirm Amethyst is working as intended
Open Vivaldi browser

**Expected behavior**
It is expected that the Vivaldi window moves to its designated location without overlap based on Amethyst preferences

**Screenshots**
Three Pane Middle 
![image](https://user-images.githubusercontent.com/84650530/166161549-b0dda93c-7892-4d39-9fe5-15daeb517aeb.png)

**Versions:**
 - macOS: Monterey 12.3.1
 - Amethyst: 0.15.6
 
**Debug Info**
```
$ /Applications/Amethyst.app/Contents/MacOS/Amethyst --debug-info

Version: 0.15.6 (93)

OS version: Version 12.3.1 (Build 21E258)

Screens:
	(0.0, 0.0, 3440.0, 1440.0) [(0.0, 0.0, 3440.0, 1440.0)]

Configuration:
use-canary-build: 0
window-resize-step: 5
mod1: (
    option,
    shift
)
ignore-menu-bar: 1
screen-padding-right: 0
floating: (
)
restore-layouts-on-launch: 1
float-small-windows: 1
mouse-resizes-windows: 1
enables-layout-hud-on-space-change: 1
debug-layout-info: 0
mouse-swaps-windows: 1
mod2: (
    option,
    shift,
    control
)
window-minimum-height: 0
new-windows-to-main: 0
focus-follows-mouse: 0
window-margin-size: 75
floating-is-blacklist: 1
screen-padding-bottom: 0
screen-padding-left: 0
enables-layout-hud: 1
follow-space-thrown-windows: 1
window-minimum-width: 0
smart-window-margins: 0
window-margins: 1
mouse-follows-focus: 1
layouts: (
    "two-pane",
    "middle-wide",
    fullscreen,
    tall
)
screen-padding-top: 0
```

**Additional context**
Sometimes it appears that it treats Vivaldi as a floating window--I cycle through the layouts but Vivaldi doesn't move. 
Sometimes if I move Vivaldi to where it's supposed to go, Amethyst will pick it up and adjust it correctly to fit the space

**Comment by Bellavene** [comment] 2022-05-02 15:15
Don't have that problem

**Comment by chen-ye** [comment] 2022-05-03 21:33
Seeing a similar issue on Edge Dev 102.0.1235.1, but not on Edge 101.0.1210.32 nor Chrome (101.0.4951.54):
![amethyst wack](https://user-images.githubusercontent.com/1904031/166570157-b6b5a5c2-9be2-4d0a-bac7-a0217af12e2e.gif)

**Comment by thekarel** [comment] 2022-05-10 16:22
I see the same issue with Firefox

**Comment by KingOfSpades** [comment] 2022-06-20 12:42
I always have this issue with Firefox (see: https://github.com/ianyh/Amethyst/issues/1119 ). I do notice it with Vivaldi more since the last few version but most of the time it works great. I think its more of a browser issue then a Amethyst issue (:

**Comment by auscompgeek** [comment] 2022-07-18 05:26
Possible duplicate of #1257?

**Comment by ianyh** [comment] 2023-02-07 01:42
Yes, it is a duplicate.

**Closed as not planned by ianyh** 2023-02-07 01:42 UTC
