### ISSUE TITLE
Sloppy focus/focus follows mouse not possible switching from iTerm2 window

### ISSUE THREAD

**Issue by TreyBlancher** [ianyh/Amethyst#314] opened 2015-07-12 20:04 UTC
Sloppy focus/focus-follows-mouse seems to work for any type of window except iTerm2.  If iTerm2 does not have focus, I must click in an iTerm2 window (or give it focus via keyboard);  simply moving the mouse cursor over an iTerm2 window does not give the iTerm2 window focus.  The converse, moving the mouse cursor away from a focused iTerm2, is also problematic;  I must click the other window on the screen (or, again, use a keyboard focus switch).

I have tried toggling the Focus Follows Mouse feature in iTerm2, with no change in behavior.

[Trello Card](https://trello.com/c/1qrtCEtE/143-amethyst-sloppy-focus-focus-follows-mouse-not-possible-switching-from-iterm2-window)

**Comment by TreyBlancher** [comment] 2015-07-21 17:25
I've also noticed this problem with HipChat, Focus Follows Mouse works except for iTerm2 and HipChat.  For iTerm2, I can FFM between iTerm2 windows, but no other windows.  HipChat I have to click on to give focus.

I'll report any other applications that do this, but I figure iTerm2 would give the best clues, since it's open source.

**Comment by emersonveenstra** [comment] 2015-08-27 13:04
Sublime Text 3 also has this problem

**Comment by vlerenc** [comment] 2017-02-13 04:42
Tried it with iTerm2 and it definitely works for me, but I am struck by #398 (MacBook Pro late 2016, macOS 10.12.3 (16D32), two monitors, was trying tall and floating). The feature doesn't work on monitor 1 for me at all, but works perfectly on monitor 2 (including iTerm2, in and out).

That feature would be totally awesome (being used to *nix). Sad, Macs don't have it, so if you have any clues how to make it work, that would be really much appreciated! Thanks a lot in advance!

**Comment by ianyh** [comment] 2017-07-13 19:33
This seems to work correctly now and the issue is quite old so I'm closing. Please feel free to reopen if you encounter it again.

**Closed by ianyh** 2017-07-13 19:33 UTC
Labels: bug, focus follows mouse
