### ISSUE TITLE
Have shortcuts for desktop changes in amethyst

### ISSUE THREAD

**Issue by Menn1s** [ianyh/Amethyst#963] opened 2020-02-25 17:37 UTC
I noticed when I worked on multiple monitors that the command to throw a window to another workspace was relative to the current space (so if I throw to WS 2, it will be the second space for a particular monitor, not the actual second workspace).

I like the relative system (because the numbering goes quite high when you have a couple desktops with multiple workspaces). I wish there were workspace switching shortcuts that acted similar to the window throwing command. These would replace the native WS switching shortcuts that depend on the actual WS number.

I have used the shortcut for moving one space left and one space right, which works as a relative switch for now. It would be much faster to have a direct switch though.

Thanks for the great app!

**Comment by ianyh** [comment] 2020-02-25 21:09
Duplicate of #911

**Closed** 2020-02-25 21:10 UTC
Labels: duplicate, enhancement
