### ISSUE TITLE
Support focus follows mouse without autoraise

### ISSUE THREAD

**Issue by Woolfe** [ianyh/Amethyst#816] opened 2019-03-21 12:00 UTC
Are there any plans to support focus follows mouse without auto-raise? 

⌃⌥-click (control-option-click) on an unfocused window switches focus to that window without raising it, and I think having a "follows mouse" version of this behaviour would be really useful in Amethyst for those who use floating windows.

**Comment by ianyh** [comment] 2019-04-12 01:58
Duplicate of #245

**Closed by ianyh** 2019-04-12 01:58 UTC

**Comment by xdgc** [comment] 2020-06-17 20:53
@ianyh I'll trust you on this if you say so, but it's not clear to me that this is a dup of #245. Without knowing implementation details, they sound like completely separate issues. Is it possible you meant #638?

If you're an X11 user, FFM and autoraise are distinct features. The use case for not autoraising is to keep one window in full view (on top of all others, i.e. raised) while input focus is on a window that is partially or fully hidden from view. This is useful for many scenarios, but as an example, imagine translating German text from a web browser to English text in an editor. You can do this with tiling, but it may be preferable to keep windows full size.

If you have FFM, you don't want to click — or to ⌃⌥-click.
