### ISSUE TITLE
What Ctrl+Option+Shift+Right actually do?

### ISSUE THREAD

**Issue by Pitometsu** [ianyh/Amethyst#661] opened 2017-11-17 10:44 UTC
I have `Ctrl+Option+Shift+COMMAND` modifier for all the actions in Preferences of *Amethyst*.
But  `Ctrl+Option+Shift+Right` hotkey isn't working for current application (e.g. in Emacs I see `<left-fringe> <drag-mouse-1> is undefined` message). How can I fix that and customize to use just expected shortcuts?
MacOS `10.13.1 (17B48)`, Amethyst `0.11.4 (52)`.

[Trello Card](https://trello.com/c/a6u2Idjn/298-amethyst-what-ctrloptionshiftright-actually-do)

**Comment by ianyh** [comment] 2018-02-02 12:22
This may mean that you don't have the shortcuts for spaces available. See https://github.com/ianyh/Amethyst#setting-up-spaces-support

**Comment by Pitometsu** [comment] 2018-02-02 13:12
No, I have `Cmd+Opt+Ctrl+` `<left>`/`<right>` shortcuts for that.

**Comment by ianyh** [comment] 2018-02-02 13:24
Amethyst is still pretty tightly coupled with the _default_ system shortcuts for spaces (in this case, <kbd>ctrl</kbd>+{<kbd>left</kbd>, <kbd>right</kbd>}, so if you've changed them then the commands are unlikely to work. There's an issue somewhere for decoupling them and I can find it later, but in the meantime you could test this by temporarily reverting your system commands for switching spaces, seeing if that works, and then updating them back to what you had. If it still doesn't work there might be something else happening.

**Comment by Pitometsu** [comment] 2018-02-02 13:28
I need this shortcuts for applications like IDE, text editor, and command line.

**Comment by uloco** [comment] 2018-08-10 11:26
There is a difference between a window creating a new space because of full screen and a dedicated new desktop space. Amethyst only works for the latter one. At first sight I thought the *throw window to space x* functionality was not working right. I think this behaviour is very misleading and should be rethought about.

**Comment by ianyh** [comment] 2018-08-10 12:46
Amethyst doesn’t create spaces at all, it only moves windows between existing spaces.

**Comment by ianyh** [comment] 2018-08-10 12:48
As for this specific issue I think this is a duplicate of #409

**Closed** 2018-08-10 12:49 UTC
Labels: duplicate, enhancement
