### ISSUE TITLE
Add option to specify default amount of main panes for wide

### ISSUE THREAD

**Issue by deiga** [ianyh/Amethyst#303] opened 2015-04-17 08:19 UTC
I have a huge external monitor with widescreen-tall layout and it is very confusing when I restart amethyst and my extra main panes vanish.

[Trello Card](https://trello.com/c/oFYEdtXE/132-amethyst-add-option-to-specify-default-amount-of-main-panes-for-wide)

**Comment by ianyh** [comment] 2015-05-12 13:55
This is basically a duplicate of #151

**Closed by ianyh** 2015-05-12 13:55 UTC
