### ISSUE TITLE
[Feature Request] Add shortcut overview like "CheatSheet" does.

### ISSUE THREAD

**Issue by Jonn3y** [ianyh/Amethyst#919] opened 2019-12-12 11:18 UTC
## System

 - **Amethyst version**:0.14.3
 - **macOS version**: 10.15.1 (19B88)

## What's the problem?
I am not able to remember all needed shortcut combinations

## Feature Request
Would it be possible to show a shortcut overview by pressing mod1 for 2-3 seconds like CheatSheet does?Im using https://www.mediaatelier.com/CheatSheet/ a lot and it would be nice to have a similar overview for Amethyst.

Screenshot: 
![cheatsheet_657972_full png](https://user-images.githubusercontent.com/11927089/70707831-63703380-1cd9-11ea-8a67-9efdd42df9d4.jpeg)

Greetings:
Jonny

**Comment by ianyh** [comment] 2019-12-19 01:08
Duplicate of #275

**Closed by ianyh** 2019-12-19 01:08 UTC
